uktrade/trade-tariff-management

.circleci/config.yml
bin/lint_js
bin/lint_ruby
package.json

- Updated the `eslint` npm packages so they actually install (there was a dependency conflict).
- Added JS linting step to CircleCI
- Added Ruby linting step to CircleCI

Lint JS and tie into CircleCI lifecycle

---

Gemfile
Gemfile.lock
config/puma.rb

Add meta_request gem for rails panel chrome extension.
Extend puma timeout in development.

Minor changes to help debugging.

---

app/interactors/workbasket_interactions/create_measures/settings_saver.rb
app/interactors/workbasket_interactions/settings_saver_base.rb
config/locales/en.yml
spec/features/workbasket/measure/measure_creation_validation_spec.rb
spec/features/workbasket/quota/quota_creation_validations_spec.rb

(I could clean up some of the duplication, but left for now as it matches the rest of the classes...will clean up all of the duplication later)

Prevent exception when an invalid commodity code is entered.

---

app/helpers/measures_helper.rb
app/services/workbasket_services/quota_savers/order_number.rb

(Also delete a duplicated method in measures_helper)

Prevent blank 'period start date' from throwing an exception

---

app/services/xml_generation/metadata.rb
app/views/xml_generation/templates/metadata.builder

Remove hardcoded correlation ID and replace with a uuid and remove non mandatory metadata.

Xml metadata

---

app/helpers/cross_check_helper.rb
app/views/shared/vue_templates/_cross_check_decision.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_quota_periods_table.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_workbasket_details.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/_block.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_quotas.html.slim
app/views/workbaskets/workflows/cross_checks/new.html.slim
spec/features/workbasket/cross_check/cross_check_spec.rb

Allow users to cross check `create quota` workbaskets

Cross check quotas

---

Gemfile
app/assets/javascripts/application.js
app/assets/javascripts/components/cross-check.js
app/controllers/workbaskets/workflows/base_controller.rb
app/interactors/workbasket_interactions/workflow/approve_base.rb
app/interactors/workbasket_interactions/workflow/cross_check.rb
app/views/workbaskets/workflows/approves/_action_links.html.slim
app/views/workbaskets/workflows/approves/_form.html.slim
app/views/workbaskets/workflows/cross_checks/_action_links.html.slim
app/views/workbaskets/workflows/cross_checks/_form.html.slim
spec/features/workbasket/cross_check/cross_check_spec.rb
spec/features/workbasket/measure/measure_creation_approval_spec.rb

Simply the workflows by removing Vue and using simple rails forms.

Remove Vue from create measures workflow pages.

---

app/views/shared/vue_templates/_footnote.html.erb
app/views/workbaskets/create_footnote/steps/main/_description.html.slim
app/views/workbaskets/edit_footnote/steps/main/_description.html.slim

https://trello.com/c/WBwHT2L7/727-data-protection-statement

Add Data Protection statement to footnote field.

---

app/value_objects/workbasket_value_objects/shared/commodity_codes_analyzer.rb

https://trello.com/c/nLOYvMnv/396-dit-tq-54-changes-to-validation-and-conformance-error-handling-40

Fix exception if no start date for measure.

---

app/helpers/approval_helper.rb
app/views/shared/vue_templates/_approve_decision.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/approves/_general.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_ready_for_export.html.slim
app/views/workbaskets/workflows/approves/_form.html.slim
app/views/workbaskets/workflows/approves/new.html.slim
app/views/workbaskets/workflows/cross_checks/_form.html.slim
spec/features/workbasket/cross_check/cross_check_spec.rb
spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb
spec/features/workbasket/main_menu_spec.rb
spec/features/workbasket/measure/measure_creation_approval_spec.rb

Cross check PR must be merged first.

Approve quotas

---

app/assets/javascripts/vue_components/quota-section.js
app/assets/stylesheets/components/quota-section.scss
app/interactors/workbasket_interactions/edit_quota/settings_extractor.rb
app/services/workbasket_services/quota_savers/base_period.rb
app/value_objects/workbasket_value_objects/create_quota/attributes_parser.rb
app/views/shared/vue_templates/_quota_section.html.erb
app/views/shared/vue_templates/_quota_sections_manager.html.erb
config/locales/en.yml
spec/support/capybara.rb

Only have a single option 'EUROs'

Add monetary Unit field for Quotas

---

app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/workflows/approves/new.html.slim

https://trello.com/c/WBwHT2L7/727-data-protection-statement

Display the footnote warning on cross check and approval pages.

---

app/services/xml_generation/download.rb
app/services/xml_generation/upload.rb
app/workers/download_xml_worker.rb
config/schedule.yml
config/sidekiq.yml

This PR implements polling our S3 bucket every 5 minutes to check for responses from HRMC.
If found then we save the XML and then move the processed files to a new directory on our S3 bucket.
Note: The directory names are placeholders, as of yet we do not know exactly where HMRC will put the response files.

Download xml

---

app/views/workbaskets/create_additional_code/edit.html.slim
app/views/workbaskets/create_certificate/edit.html.slim
app/views/workbaskets/create_footnote/edit.html.slim
app/views/workbaskets/create_geographical_area/edit.html.slim
app/views/workbaskets/create_measures/edit.html.slim
app/views/workbaskets/create_quota/edit.html.slim
app/views/workbaskets/create_regulation/edit.html.slim
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_conditions.html.slim

https://trello.com/c/QvvIxfJ9/766-miscellaneous-cosmetic-and-copy-gripes-on-create-edit-quota

Miscellaneous cosmetic and copy gripes on Create / Edit Quota

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim

So don't check it when displaying the summary.

No longer use operation date

---

app/assets/stylesheets/components/layout.scss
app/assets/stylesheets/components/main-menu.scss

As per item 2 on the checklist at https://trello.com/c/tgc4oEm7/753-fixed-width-layout
This is what the changes look like:

Ui adjust gutters

---

app/assets/javascripts/vue_components/records-grid.js
app/searches/measures/search_filters/find_measures_collection.rb
app/views/shared/vue_templates/_records_grid.html.erb
spec/unit/searches/measures/simple_filters_spec.rb

Merge after https://github.com/uktrade/trade-tariff-management/pull/82

Lock measures that arent approved

---

app/services/xml_generation/upload.rb

Reverts uktrade/trade-tariff-management#89

Revert "reference s3"

---

app/services/xml_generation/download.rb
app/services/xml_generation/upload.rb

Reverts uktrade/trade-tariff-management#86

Revert "Fix upload issue in non dev environments"

---

lib/sequel/plugins/time_machine.rb
spec/models/measure_spec.rb

Was throwing exception when it was checking for similar commodities and commodities is blank
https://trello.com/c/zdjD192z/829-creating-a-measure-with-no-commodity-code-and-with-additional-code-app-is-stuck-with-checking-data

Fixed exception when checking for ME32

---

app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim

https://trello.com/c/CvaU95Ha/802-as-an-approver-clicking-on-view-to-view-the-measure-with-status-awaiting-cds-upload-create-new-goes-to-were-sorry-but-something

Display other statuses in the 'view quota' page.

---

app/value_objects/workbasket_value_objects/shared/additional_codes_analyzer.rb
app/value_objects/workbasket_value_objects/shared/commodity_codes_analyzer.rb

catch exception and default to today's date.

Handle case where user enters crap into the date field

---

app/assets/javascripts/vue_components/quota-section.js
app/assets/javascripts/vue_components/quota-sections-manager.js

Adds confirmation dialog to remove period or section in Edit Quota.
Looks like this:
And this

Edit quota confirmations

---

app/controllers/sessions_controller.rb
app/helpers/auth_helper.rb
app/models/session_audit.rb
db/migrate/20190320142706_create_session_audits.rb
db/structure.sql

https://trello.com/c/mwfsFpP7/828-ensure-all-user-logons-are-logged

Audit site usage

---

app/services/xml_generation/upload.rb

Trello card: https://trello.com/c/FGg6UBNy/859-change-xml-upload-file-names

Change names of uploaded files to fit hmrc's new naming convention

---

app/controllers/workbaskets/bulk_edit_of_measures_controller.rb
app/helpers/workbasket_helper.rb

Before approval, user should be able to withdraw.

Allow "Bulk Edit Measures" workbasket to be withdrawn/edit 

---

app/assets/stylesheets/components/find-items.scss
app/assets/stylesheets/components/quota-show-page.scss
app/assets/stylesheets/components/tables.scss
app/views/shared/vue_templates/_records_grid.html.erb

Needed to align table display with UX/design intent
Improves spacing between columns, fixes VueJS implementation error, fixes previous 'locked' symbol implementation by adding correct table heading/markup structure

Fix: Table layouts, column sizing

---

app/assets/stylesheets/components/tables.scss

The table body was misaligned
This change aligns table body with table headings
Before:
After:

Fix: Bulk edit measures table heading/body alignment

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_measures/steps/review_and_submit/_message.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim

Prior to this change, it was ugly
This change makes it a bit less ugly...
...still some pretty ugly duplication though

Refact: clean up some code when displaying codes

---

app/models/workbaskets/workbasket.rb

Prior to this change, when we edited a 'edit bulk measure' workbasket
it created multiple measures and sent them all in the xml. The expected
behaviour is that 1 new measure is created for every measure that is edited,
i.e the old one is end dated and the new one is created.
This bug meant that every additional edit added an extra measure. i.e if we
withdrew/edited the workbasket 3 times there would be 4 measures.
This change deletes the previous edit everytime we move a bulk edit measure
workbasket into the editing state so that only the original measure, and one edit
ever exists.
Trello card: https://trello.com/c/U9QXnzAV/894-additional-measures-being-created

Fix: Bug causing multiple measures to be created

---

app/views/shared/vue_templates/_measure_component.html.erb

Prior to this change, the Qualifier selector in duties was always disabled due to a missing semi-colon
This change adds a semi colon and it works!

Fix: Disabling duties, qualifier was always disabled

---

app/assets/javascripts/components/find-additional-codes.js
app/searches/additional_codes/search.rb
app/searches/additional_codes/search_filters/additional_code.rb
app/searches/additional_codes/search_filters/description.rb
app/searches/additional_codes/search_filters/find_additional_codes_collection.rb
app/views/additional_codes/additional_codes/_search_form.html.erb

Prior to this change, Description search didn't work, some unnecessary search fields and options were on the page.
This change fixes the description search 
and removes the search fields:
- valid to
- author
- date of
- last updated by
https://uktrade.atlassian.net/browse/TARIFFS-55
https://uktrade.atlassian.net/browse/TARIFFS-195

Fix: Additional Code search

---

app/views/workbaskets/bulk_edit_of_measures/submitted_for_cross_check.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_geographical_area/submitted_for_cross_check.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_measures/submitted_for_cross_check.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/_actions_allowed.html.slim

Prior to this change, withdraw link was not working on some places
This change fixes all withdraw workbasket links

Fix: Withdraw Workbasket confirmation dialog

---

app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb

Prior to this change users would get errors adding a group to a country
in edit.
This change fixes this issue.

Fix: Adding group membership to edited country

---

app/assets/javascripts/components/find-additional-codes.js
app/views/additional_codes/additional_codes/_search_form.html.erb

Prior to this change, an exception would be thrown if an invalid date
was entered.
This change checks before submitting the form.
https://uktrade.atlassian.net/browse/TARIFFS-55

Fix: Check valid date in additional code search

---

app/assets/javascripts/vue_components/edit-geographical-area-membership-popup.js
app/views/shared/vue_templates/_edit_geographical_area_membership_popup.html.slim

Reverts uktrade/trade-tariff-management#253

Revert "Fix: Delete membership box"

---

app/views/workbaskets/create_geographical_area/steps/review_and_submit/_geographical_areas.html.slim

Prior to this change, column width was relative to data
This change fixes the layout by using columns
See: [https://uktrade.atlassian.net/browse/TARIFFS-232](https://uktrade.atlassian.net/browse/TARIFFS-232)
**Before:**
**After:**

Fix align issue on Geographical areas approval page

---

app/assets/javascripts/components/create_additional_code.js
app/assets/javascripts/components/measure_form.js
app/assets/javascripts/components/quota-form.js
app/assets/javascripts/components/regulation-form.js
app/assets/javascripts/components/workbaskets/create-certificate.js
app/assets/javascripts/components/workbaskets/create-footnote.js
app/assets/javascripts/components/workbaskets/create_geographical_area.js
app/assets/javascripts/components/workbaskets/edit-certificate.js
app/assets/javascripts/components/workbaskets/edit-footnote.js
app/assets/javascripts/components/workbaskets/edit-geographical-area.js
app/views/workbaskets/create_measures/_form.html.slim
app/views/workbaskets/create_quota/_form.html.slim
app/views/workbaskets/create_regulation/_form.html.slim
app/views/workbaskets/shared/_custom_errors_block.html.slim

Fix UX when errors
Prior to this change, user could not see that there were form errors
This change focus to error summary when it exists on top of the page
Related to : [TARIFFS-125](https://uktrade.atlassian.net/browse/TARIFFS-125)

Improve UX when errors

---

app/views/additional_codes/bulks/work_with_selected.html.erb
app/views/certificates/certificates/search/_download_link.html.slim
app/views/certificates/certificates/search/_form.html.slim
app/views/footnotes/footnotes/search/_download_link.html.slim
app/views/footnotes/footnotes/search/_form.html.slim
app/views/geo_areas/geo_areas/search/_form.html.slim
app/views/measures/bulks/work_with_selected_measures.html.erb
app/views/quotas/bulks/work_with_selected_measures.html.erb
app/views/regulations/_form.html.slim
app/views/regulations/search/_form.html.slim
app/views/workbaskets/edit_certificate/steps/main/_description_validity_start_date.html.slim
app/views/workbaskets/edit_certificate/steps/main/_operation_date.html.slim
app/views/workbaskets/edit_footnote/steps/main/_description_validity_start_date.html.slim
app/views/workbaskets/edit_footnote/steps/main/_operation_date.html.slim
app/views/workbaskets/edit_geographical_area/steps/main/_description_validity_start_date.html.slim
app/views/workbaskets/edit_geographical_area/steps/main/_operation_date.html.slim
app/views/workbaskets/main_menu_parts/_withdraw_confirmation_popup.html.slim

This commit fixes some UI issues
**Resolves:**  [https://uktrade.atlassian.net/browse/TARIFFS-285](https://uktrade.atlassian.net/browse/TARIFFS-285)

Fix UI issues

---

.circleci/config.yml
README.md
app/views/layouts/application.html.erb
app/views/sessions/destroy.erb
app/workers/test_worker.rb
bin/deploy
db/structure.sql

Prior to this change, there were some outsourced references
This change replaces those
Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-296](https://uktrade.atlassian.net/browse/TARIFFS-296)

Fix references to bitzesty

---

app/controllers/workbaskets/edit_nomenclature_controller.rb
app/controllers/workbaskets/manage_nomenclatures_controller.rb
app/forms/workbasket_forms/edit_nomenclature_form.rb
app/forms/workbasket_forms/manage_nomenclature_form.rb
app/interactors/workbasket_interactions/edit_nomenclature/initial_validator.rb
app/interactors/workbasket_interactions/edit_nomenclature/settings_saver.rb
app/validators/goods_nomenclature_description_period_validator.rb
app/views/nomenclature/_sections_header.html.erb
app/views/workbaskets/edit_nomenclature/edit.html.erb
app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/manage_nomenclatures/new.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb
config/locales/en.yml

https://uktrade.atlassian.net/browse/TARIFFS-214

New: Conformance rules for edit nomenclature description

---

app/validators/footnote_validator.rb
app/validators/goods_nomenclature_description_period_validator.rb
app/validators/measure_validator.rb
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/approves/_general.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_approval_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_cds_error.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_cross_check_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_ready_for_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_ready_for_export.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/view/_sent_to_cds.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_ready_for_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_ready_for_export.html.slim

This change replaces Nomenclature word with Goods classification
Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-326](https://uktrade.atlassian.net/browse/TARIFFS-326)

Fix: Replace Nomenclature word

---

app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb

This change correctly updates geographical area and the related objects and renders the corresponding XML based on the requirements outline here: https://uktrade.atlassian.net/wiki/spaces/TARIFFSALPHA/pages/844759391/Creating+XML+for+additional+codes+certificates+geographical+areas+footnotes+and+good+nomenclatures
Resolves this card: https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-303

Geo area xml

---

app/views/measures/bulks/_table_top.html.erb
app/views/quotas/bulks/_table_top.html.erb
app/views/shared/bulks/_table_top.html.erb

Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-300](https://uktrade.atlassian.net/browse/TARIFFS-300)

Remove bulk word from dropdown

---

app/views/shared/vue_templates/additional_codes/_delete.html.erb

Resolves: [TARIFFS-292](https://uktrade.atlassian.net/browse/TARIFFS-292)
**After**

Show correct message when deleting add.codes

---

README.md
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_approval.html.slim

Resolves: [TARIFFS-346](https://uktrade.atlassian.net/browse/TARIFFS-346)
**Before**
**After**

Fix nomenclature cross-check links

---

app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb

Resolves: [TARIFFS-358](https://uktrade.atlassian.net/browse/TARIFFS-358)

Fix dates format

---

app/assets/stylesheets/components/layout.scss
app/value_objects/workbasket_value_objects/attributes_parser_base.rb
app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
app/views/log_in/index.html.erb
app/views/workbaskets/create_measures/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim
spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb

Resolves: [TARIFFS-359](https://uktrade.atlassian.net/browse/TARIFFS-359)
As part of this commit, some generic layout fixes also took place

Change regulation id to 8 digits

---

app/interactors/workbasket_interactions/edit_nomenclature/settings_saver.rb
app/views/nomenclature/chapters/show.html.erb
app/views/nomenclature/sections/show.html.erb

Prior to this change, Chapters and Headings couldn't be managed.
https://uktrade.atlassian.net/browse/TARIFFS-324

New: Nomenclature - Manage Chapters and Headers

---

app/views/workbaskets/workflows/cross_checks/new.html.slim

Resolves: [TARIFFS-360](https://uktrade.atlassian.net/browse/TARIFFS-360)
**Before:**
**After**

Show summary on cross-check

---

app/helpers/auth_helper.rb

Reverts uktrade/trade-tariff-management#352

Revert "fix: session audit log bug"

---

app/views/workbaskets/edit_nomenclature/edit.html.erb
app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

**Relates:** [https://uktrade.atlassian.net/browse/TARIFFS-326](https://uktrade.atlassian.net/browse/TARIFFS-326)

Add commodity  word

---

app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim

This change implements the withdraw link.
https://uktrade.atlassian.net/browse/TARIFFS-371

New: Can withdraw workbasket on summary page

---

app/views/workbaskets/create_geographical_area/steps/review_and_submit/_geographical_areas.html.slim

**Relates, Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-358](https://uktrade.atlassian.net/browse/TARIFFS-358)

Fix date format on geographical areas

---

app/controllers/goods_nomenclatures_controller.rb
app/views/goods_nomenclatures/_tree_node.html.erb
app/views/goods_nomenclatures/show.html.erb
app/views/nomenclature/_sections_header.html.erb
config/routes.rb
lib/tree_node.rb

This change allows users to search for Commodities by code.
https://uktrade.atlassian.net/browse/TARIFFS-206

New: Search for commodity by code

---

app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb

Add new label to edit nomenclature

---

app/helpers/cross_check_helper.rb

**Relates:** [https://uktrade.atlassian.net/browse/TARIFFS-331](https://uktrade.atlassian.net/browse/TARIFFS-331)

Add missing cross-check headers

---

app/controllers/measures/measures_controller.rb
app/models/measure.rb
app/views/measures/measures/_search_page.html.slim

This change allows the results to be downloaded.
Currently we do not limit the download, but we do need to only allow
this if the number of results is less than 'x'. We need to test this on
DEV and UAT and decide what value 'x' is.
https://uktrade.atlassian.net/browse/TARIFFS-370

New: Allow download of search measures as a CSV file.

---

app/views/nomenclature/sections/index.html.erb

**Resolves:**  [https://uktrade.atlassian.net/browse/TARIFFS-364](https://uktrade.atlassian.net/browse/TARIFFS-364)

Change code copy to section

---

app/assets/javascripts/vue_components/additional_codes/change-validity-period.js
app/views/shared/vue_templates/additional_codes/_change_validity_period.html.erb

**Resolves comment on:**  [TARIFFS-365](https://uktrade.atlassian.net/browse/TARIFFS-365)

Fix vaildation problem

---

app/views/workbaskets/create_footnote/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_footnote/show.html.slim
app/views/workbaskets/edit_footnote/submitted_for_cross_check.html.slim

**Resolves:**  [https://uktrade.atlassian.net/browse/TARIFFS-390](https://uktrade.atlassian.net/browse/TARIFFS-390)

Remove 'Not implemented' on footnotes

---

app/views/workbaskets/create_regulation/steps/review_and_submit/_details.html.slim

This commit remove some info from the details list
as requested.
**Resolves**  [TARIFFS-271](https://uktrade.atlassian.net/browse/TARIFFS-271)

Remove info from details list

---

app/helpers/approval_helper.rb

Relates: [https://uktrade.atlassian.net/browse/TARIFFS-388](https://uktrade.atlassian.net/browse/TARIFFS-388)

Add missing approval title

---

Gemfile
Gemfile.lock
app/assets/javascripts/cable.js
app/views/layouts/application.html.erb
config/cable.yml
config/environments/production.rb

Copied from a blog...no idea if this will work as I am pretty ignorant
on cf paas.
http://engineering.pivotal.io/post/using-action-cable-with-cloud-foundry/

Fix: Paas config for action cable

---

app/assets/javascripts/vue_components/date-gds.js
app/views/footnotes/footnotes/search/_form.html.slim
app/views/shared/vue_templates/_date_gds.html.erb

**Resolves** [https://uktrade.atlassian.net/browse/TARIFFS-401](https://uktrade.atlassian.net/browse/TARIFFS-401)

Use date-gds component on find footnotes

---

app/views/workbaskets/create_additional_code/_breadcrumbs.html.slim

**Relates:** [https://uktrade.atlassian.net/browse/TARIFFS-388](https://uktrade.atlassian.net/browse/TARIFFS-388)

Fix breadcrumb on view additional codes

---

app/assets/javascripts/vue_components/date-gds.js
app/views/shared/vue_templates/_date_gds.html.erb
app/views/shared/vue_templates/_quota_section.html.erb
app/views/workbaskets/create_additional_code/steps/main/_start_end_dates.html.slim
app/views/workbaskets/create_certificate/steps/main/_operation_date.html.slim
app/views/workbaskets/create_certificate/steps/main/_validity_period.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_validity_period.html.slim
app/views/workbaskets/create_measures/steps/main/_start_end_dates.html.slim
spec/features/workbasket/geographical_area/geographical_area_creation_spec.rb
spec/features/workbasket/measure/measure_creation_spec.rb
spec/features/workbasket/measure/measure_creation_validation_spec.rb
spec/features/workbasket/quota/quota_creation_validations_spec.rb
spec/features/workbasket/quota/quota_spec.rb

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-402](https://uktrade.atlassian.net/browse/TARIFFS-402)

Use date-gds component on create view forms

---

app/views/workbaskets/create_footnote/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_footnote/show.html.slim
app/views/workbaskets/edit_footnote/submitted_for_cross_check.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-390](https://uktrade.atlassian.net/browse/TARIFFS-390)

Fix withdrawn links on footnotes

---

app/interactors/workbasket_interactions/edit_footnote/settings_saver.rb
app/views/workbaskets/edit_footnote/steps/main/_validity_period.html.slim

__NOTE:__ The following PR needs to be merged before this one: https://github.com/uktrade/trade-tariff-management/pull/428
This commit allows editing of footnote descriptions where the new description has a different start date to the old description.

Edit footnotes business logic

---

app/helpers/approval_helper.rb
app/helpers/cross_check_helper.rb
app/helpers/workbasket_workflow_helper.rb
app/views/measures/bulks/edit.html.slim
app/views/measures/bulks/work_with_selected_measures.html.erb
app/views/measures/measures/_search_page.html.slim
app/views/quotas/bulks/configure_cloned.erb
app/views/quotas/bulks/edit_quota/_breadcrumbs.html.slim
app/views/quotas/bulks/edit_quota_measures/_edit.html.slim
app/views/quotas/bulks/show.html.slim
app/views/quotas/bulks/work_with_selected.erb
app/views/quotas/quotas/_search_page.html.slim
app/views/workbaskets/bulk_edit_of_measures/show.html.slim
app/views/workbaskets/create_additional_code/_breadcrumbs.html.slim
app/views/workbaskets/create_certificate/_breadcrumbs.html.slim
app/views/workbaskets/create_geographical_area/_breadcrumbs.html.slim
app/views/workbaskets/create_geographical_area/show.html.slim
app/views/workbaskets/create_measures/_breadcrumbs.html.slim
app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/_breadcrumbs.html.slim
app/views/workbaskets/create_quota/show.html.slim
app/views/workbaskets/create_regulation/_breadcrumbs.html.slim
app/views/workbaskets/edit_geographical_area/show.html.slim
app/views/xml_generation/exports/index.html.slim

Breadcrumbs were not consistent across the app.
- Added missing cases inside the helper files 
- Renamed links to mach pages and be consistent
- Fixed create breadcrumb journeys by remove edit links
**Resolves:** [TARIFFS-388](https://uktrade.atlassian.net/browse/TARIFFS-388)

Improve breadcrumbs

---

app/forms/workbasket_forms/edit_nomenclature_form.rb
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-422](https://uktrade.atlassian.net/browse/TARIFFS-422)

Unset default date on edit description

---

app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_approval.html.slim

The links have been fixed as part of another story. This commit only
fixes the copy issues
**Resolves:**  [TARIFFS-407](https://uktrade.atlassian.net/browse/TARIFFS-407)

Fix grammar on cross-checked messages

---

app/helpers/workbasket_workflow_helper.rb

**Relates:** [https://uktrade.atlassian.net/browse/TARIFFS-388](https://uktrade.atlassian.net/browse/TARIFFS-388)

Fix regulations breadcrumb

---

config/schedule.yml

This commit temporarily disables the download worker in order to fully test the upload functionality.

Fix: Stop download worker running.

---

app/views/shared/vue_templates/_quota_section.html.erb
db/structure.sql

**Relates:** [https://uktrade.atlassian.net/browse/TARIFFS-423](https://uktrade.atlassian.net/browse/TARIFFS-423)

Hide 'Remove Period' if there’s only 1 custom period

---

db/structure.sql

I dont understand why we need to revert the structure SQL but here you go :)

Revert structure.sql

---

app/views/workbaskets/create_footnote/show.html.slim
app/views/workbaskets/edit_footnote/show.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-449](https://uktrade.atlassian.net/browse/TARIFFS-449)

Fix 'Edit footnote' link

---

app/views/additional_codes/additional_codes/_search_form.html.erb
app/views/certificates/certificates/search/_form.html.slim
app/views/footnotes/footnotes/search/_form.html.slim
app/views/geo_areas/geo_areas/search/_form.html.slim
app/views/measures/bulks/_action_buttons.html.slim
app/views/measures/measures/_search_form.html.erb
app/views/quotas/bulks/_action_buttons.html.slim
app/views/quotas/quotas/_search_form.html.erb
app/views/regulations/search/_form.html.slim
app/views/shared/bulks/_action_buttons.html.slim
app/views/workbaskets/create_additional_code/_action_links.html.slim
app/views/workbaskets/create_certificate/_action_links.slim
app/views/workbaskets/create_footnote/_action_links.html.slim
app/views/workbaskets/create_geographical_area/_action_links.html.slim
app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/show.html.slim
app/views/workbaskets/create_regulation/_action_links.html.slim
app/views/workbaskets/edit_certificate/_action_links.html.slim
app/views/workbaskets/edit_footnote/_action_links.html.slim
app/views/workbaskets/edit_geographical_area/_action_links.html.slim
app/views/workbaskets/edit_nomenclature/_action_links.html.slim
app/views/workbaskets/manage_nomenclatures/new.html.erb
app/views/workbaskets/shared/_action_links.html.slim
app/views/workbaskets/workflows/approves/_action_links.html.slim
app/views/workbaskets/workflows/cross_checks/_action_links.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-446](https://uktrade.atlassian.net/browse/TARIFFS-446)

Fix find form links

---

app/views/workbaskets/create_footnote/show.html.slim
app/views/workbaskets/edit_footnote/show.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-450](https://uktrade.atlassian.net/browse/TARIFFS-450)

Fix view footnote breadcrumb

---

app/assets/javascripts/components/validators/additional_codes.js
app/interactors/workbasket_interactions/create_additional_code/settings_saver.rb
app/views/workbaskets/create_additional_code/steps/main/_additional_codes.html.slim
app/views/workbaskets/create_additional_code/steps/main/_start_end_dates.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-512](https://uktrade.atlassian.net/browse/TARIFFS-512)
**After:**

Fix validation on create additional codes

---

app/helpers/workbasket_workflow_helper.rb

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-522](https://uktrade.atlassian.net/browse/TARIFFS-522)
**Related designs:**
[https://uktrade.atlassian.net/wiki/spaces/TARIFFSALPHA/pages/469008587/View+Cross-Check+Approve+Measures](https://uktrade.atlassian.net/wiki/spaces/TARIFFSALPHA/pages/469008587/View+Cross-Check+Approve+Measures)

Fix withdraws links not showing bug

---

app/interactors/workbasket_interactions/create_certificate/initial_validator.rb
app/interactors/workbasket_interactions/edit_certificate/initial_validator.rb
app/views/workbaskets/create_certificate/steps/main/_description.html.slim
app/views/workbaskets/edit_certificate/steps/main/_description.html.slim

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-527

Limit certificate description

---

app/controllers/quotas/bulks_controller.rb
app/helpers/workbasket_helper.rb
app/views/quotas/bulks/submitted_for_cross_check.html.slim

**Relates:** https://uktrade.atlassian.net/browse/TARIFFS-414
**IMPORTANT**
Please read my  comment on the above ticket and update regarding.

Fix edit quotas link options on submission

---

app/interactors/workbasket_interactions/edit_certificate/settings_saver.rb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-498

Fix: Assign correct validity start date to certificate description

---

app/views/shared/bulks/_action_buttons.html.slim
app/views/workbaskets/create_regulation/show.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-521](https://uktrade.atlassian.net/browse/TARIFFS-521)

Fix return to main menu links on create regulation

---

app/helpers/approval_helper.rb
app/views/workbaskets/edit_certificate/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_edit_certificate.html.slim
app/views/workbaskets/workflows/approves/new.html.slim
app/views/workbaskets/workflows/cross_checks/new.html.slim

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-529

Update certificates summary page

---

app/views/workbaskets/create_regulation/show.html.slim
app/views/workbaskets/create_regulation/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_regulation/steps/review_and_submit/_message.html.slim
app/views/workbaskets/create_regulation/workflow_screens_parts/notifications/_block.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-465](https://uktrade.atlassian.net/browse/TARIFFS-465)

Fix regulations view page data

---

app/assets/javascripts/components/workbaskets/create-quota_association.js
app/controllers/quota_associations/quota_associations_controller.rb
app/decorators/workbaskets/quota_association_settings_decorator.rb
app/views/workbaskets/create_quota_association/edit.html.erb
app/views/workbaskets/create_quota_association/new.html.erb

Prior to this commit.
- Locking coefficient for associations was being performed for EQ type but should be NM type
- Styling of errors was not correct.
- Quota Definitions were being listed that started in the past.
- Order of Quota Associations index was not correct
https://uktrade.atlassian.net/browse/TARIFFS-454
https://uktrade.atlassian.net/browse/TARIFFS-456

Fix: small changes for quota association

---

app/views/workbaskets/create_regulation/show.html.slim
app/views/workbaskets/edit_regulation/show.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-465](https://uktrade.atlassian.net/browse/TARIFFS-465)

Remove duplicate edit links

---

app/views/certificates/certificates/search/_form.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-526](https://uktrade.atlassian.net/browse/TARIFFS-526)

Use date-gds at find certificates

---

app/assets/javascripts/components/validators/additional_codes.js

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-528](https://uktrade.atlassian.net/browse/TARIFFS-528)

Fix validation bugs on create additional codes

---

app/views/additional_codes/bulks/show.html.slim
app/views/quotas/bulks/show.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-581](https://uktrade.atlassian.net/browse/TARIFFS-581)

Fix headings on show pages

---

app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim

**Resolves** [https://uktrade.atlassian.net/browse/TARIFFS-519](https://uktrade.atlassian.net/browse/TARIFFS-519)

Fix title heading

---

app/views/workbaskets/create_regulation/steps/_review_and_submit.html.slim

**Resolves**  [https://uktrade.atlassian.net/browse/TARIFFS-573](https://uktrade.atlassian.net/browse/TARIFFS-573)

Remove not reuqired message from review page

---

db/migrate/20191021140811_create_quota_suspension_workbasket_settings.rb
db/structure.sql

Migration for 'create quota suspension workbasket settings'

Add migration for quota suspension

---

app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_certificate/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/create_quota_association/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/create_quota_association/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_certificate/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim

There was a requirement from Vincent to align confirmation messages. Changes took place based on provided
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-592](https://uktrade.atlassian.net/browse/TARIFFS-592)

Fix confirmation messages

---

app/views/workbaskets/create_quota_association/show.html.slim

Added "Return to main menu link" to quota associations
**Resolves** [https://uktrade.atlassian.net/browse/TARIFFS-521](https://uktrade.atlassian.net/browse/TARIFFS-521)

Add missing link to quota show page

---

app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/edit_regulation/show.html.slim
app/views/workbaskets/edit_regulation/workflow_screens_parts/_actions_allowed.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-522](https://uktrade.atlassian.net/browse/TARIFFS-522)

Add missing withdraw links

---

app/forms/workbasket_forms/create_quota_suspension_form.rb
app/views/workbaskets/create_quota_suspension/edit.html.erb
app/views/workbaskets/create_quota_suspension/new.html.erb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-532

Suspend quota bugs

---

app/views/additional_codes/bulks/edit.html.slim

**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-520](https://uktrade.atlassian.net/browse/TARIFFS-520)

Fix heading on bulk additional codes show page

---

.circleci/config.yml
app/views/workbaskets/main_menu_parts/_main_menu.html.slim

Add the link to reference app which is using the env variable "**TARIFF_TRADE_APPLICATION_URL**". I have also updated vault with the required values.
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-382](https://uktrade.atlassian.net/browse/TARIFFS-382)

Add Link to Main menu to Create reference documents

---

app/helpers/workbasket_workflow_helper.rb
app/views/workbaskets/create_quota_association/edit.html.erb
app/views/workbaskets/create_quota_association/show.html.slim

Fixed breadcrumbs just on create journey
**Relates:** [git push --set-upstream origin fix/TARIFFS-591]( git push --set-upstream origin fix/TARIFFS-591)

Fix quota associations create breadcrumbs

---

app/assets/stylesheets/components/layout.scss
app/controllers/quota_suspensions/quota_suspensions_controller.rb
app/models/quota_suspension_period.rb
app/views/quota_suspensions/quota_suspensions/index.html.erb

Fixes issues relating to this card:
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-536

View suspend quota bugs

---

app/helpers/workbasket_helper.rb
app/views/workbaskets/create_quota_association/submitted_for_cross_check.html.slim
app/views/workbaskets/create_quota_suspension/edit.html.erb
app/views/workbaskets/create_quota_suspension/submitted_for_cross_check.html.slim

Fixes multiple copy issues/incorrect links

Fix quota suspension copy

---

app/views/workbaskets/delete_quota_association/new.html.erb
app/views/workbaskets/delete_quota_association/submitted_for_cross_check.html.slim

Fix font on 'submitted' screen.
Change cancel url
https://uktrade.atlassian.net/browse/TARIFFS-552

Fix: Minor Quota Association Deletion issues

---

app/helpers/workbasket_helper.rb
app/views/workbaskets/create_nomenclature/edit.html.erb
app/views/workbaskets/create_nomenclature/show.html.erb
app/views/workbaskets/create_nomenclature/submitted_for_cross_check.html.slim

https://uktrade.atlassian.net/browse/TARIFFS-202

Fix feedback from QA for create nomenclature

---

app/views/workbaskets/bulk_edit_of_measures/show.html.slim
app/views/workbaskets/create_certificate/show.html.slim
app/views/workbaskets/edit_certificate/show.html.slim
app/views/workbaskets/edit_geographical_area/show.html.slim

https://uktrade.atlassian.net/browse/TARIFFS-471

Fix: Some links to edit/withdraw were not working on the view pages

---

app/views/workbaskets/create_nomenclature/edit.html.erb
app/views/workbaskets/edit_nomenclature/edit.html.erb
app/views/workbaskets/manage_nomenclatures/new.html.erb

In Nomenclature pages the cancel button would return to the Home Page.
https://uktrade.atlassian.net/browse/TARIFFS-640

Change 'Cancel' so that it goes back instead of home

---

app/assets/stylesheets/components/select.scss

Prior to this change, Matt wasn't happy.
This change will make Matt happy.
https://uktrade.atlassian.net/browse/TARIFFS-623

Fix: Style for selectize-input component

---

app/controllers/quota_blocking_periods/quota_blocking_periods_controller.rb
app/views/quota_blocking_periods/quota_blocking_periods/index.html.erb
app/views/workbaskets/main_menu_parts/_main_menu.html.slim

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-541

New: Add 'View Quota Blocking Periods' functionality

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/select.scss
app/views/shared/vue_templates/_condition.html.erb
app/views/workbaskets/create_measures/steps/duties_conditions_footnotes/_duty_expression.html.slim

https://uktrade.atlassian.net/browse/TARIFFS-30
(Also sneaked in a couple of CSS changes and hidden some explanation
text until that feature is ready)

Fix: don't display Action and Duties until Condition selected

---

app/controllers/quota_blocking_periods/quota_blocking_periods_controller.rb
app/models/quota_blocking_period.rb
app/views/quota_blocking_periods/quota_blocking_periods/index.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_quota_blocking_period.html.erb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-541

View quota blocking period bugs

---

app/forms/workbasket_forms/edit_create_quota_blocking_period_form.rb
app/views/workbaskets/create_quota_blocking_period/edit.html.erb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-538

Create quota blocking period bugs 2

---

app/assets/stylesheets/components/layout.scss
app/views/workbaskets/create_regulation/steps/main/_regulation_identifier.html.slim
app/views/workbaskets/create_regulation/steps/main/_validity_period.html.slim
app/views/workbaskets/edit_regulation/edit.html.slim
app/views/workbaskets/edit_regulation/steps/main/_regulation_identifier.html.slim
app/views/workbaskets/edit_regulation/steps/main/_validity_period.html.slim
app/views/workbaskets/shared/regulations/_regulation_group_help_text.html.erb
app/views/workbaskets/shared/regulations/_regulation_identifier_help_text.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-607
https://uktrade.atlassian.net/browse/TARIFFS-608

Fix: Help text for regulation

---

app/views/additional_codes/bulks/work_with_selected.html.erb
app/views/measures/bulks/work_with_selected_measures.html.erb
app/views/quotas/bulks/configure_cloned.erb
app/views/quotas/bulks/work_with_selected.erb
app/views/quotas/bulks/work_with_selected_measures.html.erb
app/views/shared/vue_templates/_change_validity_period.html.erb
app/views/workbaskets/create_additional_code/steps/main/_additional_codes.html.slim
app/views/workbaskets/create_certificate/_conformance_rules_container.html.slim
app/views/workbaskets/create_certificate/steps/main/_validity_period.html.slim
app/views/workbaskets/create_footnote/_conformance_rules_container.html.slim
app/views/workbaskets/create_geographical_area/_conformance_rules_container.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_quota_periods_table.html.slim
app/views/workbaskets/create_quota_association/new.html.erb
app/views/workbaskets/delete_quota_association/new.html.erb
app/views/workbaskets/delete_quota_suspension/new.html.erb
app/views/workbaskets/edit_certificate/_conformance_rules_container.html.slim
app/views/workbaskets/edit_footnote/_conformance_rules_container.html.slim
app/views/workbaskets/edit_geographical_area/_conformance_rules_container.html.slim
app/views/workbaskets/edit_nomenclature/_conformance_rules_container.html.slim
app/views/workbaskets/shared/_custom_errors_block.html.slim
app/views/workbaskets/shared/_errors_container.html.slim
config/locales/en.yml

https://uktrade.atlassian.net/browse/TARIFFS-610
https://uktrade.atlassian.net/browse/TARIFFS-664

Fix: Lots of typos

---

app/assets/javascripts/components/measure_form.js
app/controllers/goods_nomenclatures_controller.rb

https://uktrade.atlassian.net/browse/TARIFFS-645

New: Allow searching for future commodity codes on create Measure

---

app/controllers/workbaskets/reassigns_controller.rb
app/forms/workbasket_forms/reassigns_form.rb
app/models/workbaskets/workbasket.rb
app/views/workbaskets/main_menu_parts/_actions.html.slim
app/views/workbaskets/reassigns/create.html.slim
app/views/workbaskets/reassigns/new.html.erb
app/views/workbaskets/reassigns/new.html.slim
config/routes.rb
spec/features/workbasket/reassign/reassign_workbasket_spec.rb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-649
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-650
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-651

Reassign workbasket

---

app/forms/workbasket_forms/edit_edit_quota_blocking_period_form.rb
app/views/workbaskets/edit_quota_blocking_period/edit.html.erb

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-540

Edit quota blocking bugs 3

---

app/views/workbaskets/edit_nomenclature/edit.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-691

Fix: Don't force 2 digits in date fields (Edit Nomenclature)

---

app/assets/stylesheets/components/alert.scss
app/assets/stylesheets/components/layout.scss
app/assets/stylesheets/components/main-menu.scss
app/views/layouts/application.html.erb
app/views/workbaskets/index.html.slim
app/views/workbaskets/main_menu_parts/_main_menu.html.slim
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

https://uktrade.atlassian.net/browse/TARIFFS-657

New: Zhoozh-up the main menu and header

---

app/assets/stylesheets/components/layout.scss
app/views/workbaskets/index.html.slim
spec/features/workbasket/main_menu_spec.rb

https://uktrade.atlassian.net/browse/TARIFFS-657

Fix: Header spacing and "You are not working with any workbaskets text"

---

app/assets/stylesheets/components/select.scss

https://uktrade.atlassian.net/browse/TARIFFS-681

Fix: Selectize changes height when selecting items.

---

app/assets/stylesheets/components/select.scss

https://uktrade.atlassian.net/browse/TARIFFS-681

Fix: Final(?) height changes for selectize

---

app/assets/stylesheets/components/table.scss

https://uktrade.atlassian.net/browse/TARIFFS-700

Fix: Change th and td aligment for .table

---

app/services/workbasket_services/quota_savers/order_number.rb
app/validators/quota_order_number_origin_validator.rb
app/validators/quota_order_number_validator.rb
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim

This change handles the cases where a Quota Order Number (QON) already
exists, which indicates we should 'edit' the existing QON.
https://uktrade.atlassian.net/browse/TARIFFS-614
https://uktrade.atlassian.net/browse/TARIFFS-615

New handle quota edits

---

app/views/workbaskets/shared/steps/main/_check_a_commodity_code_description.html.slim

https://uktrade.atlassian.net/browse/TARIFFS-645

Fix: Show help message on Quota page for commodity search

---

app/assets/stylesheets/components/layout.scss
app/views/goods_nomenclatures/_tree_node_content.html.erb
app/views/goods_nomenclatures/show.html.erb
app/views/nomenclature/chapters/show.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-682

New: Add indent column to Commodity tables

---

Gemfile.lock

https://github.com/advisories/GHSA-hrqr-hxpp-chr3

Fix: Rack security issue

---

app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/controllers/workbaskets/base_controller.rb
app/interactors/workbasket_interactions/create_measures/settings_saver.rb
app/views/workbaskets/create_measures/steps/_main.html.slim

https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-684
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-701

Measure commodity code validation

---

app/views/nomenclature/chapters/show.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-682

Fix: Small width adjustment on chapters table.

---

app/views/goods_nomenclatures/show.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-682

Fix layout for goods nomenclature

---

app/views/workbaskets/edit_nomenclature/workflow_screens_parts/_workbasket_details.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_edit_nomenclatures.html.erb

https://uktrade.atlassian.net/browse/TARIFFS-643

Fix: Workbasket details showing twice, on approve edit nomenclature
