app/controllers/workbaskets/base_controller.rb
app/controllers/workbaskets/edit_certificate_controller.rb
app/controllers/workbaskets/edit_footnote_controller.rb
app/controllers/workbaskets/edit_geographical_area_controller.rb
app/models/workbaskets/workbasket.rb
spec/support/shared_contexts/form_savers/regulation_saver_base_context.rb

Removes `Workbaskets::Workbasket.buld_new_workbasket!`.
😅 This method is redundant and unnecessary; it doesn't do anything more than `#create` already does and is misleadingly-named, since it saves the record rather than just builds it. Also, it was mis-spelled, which was annoying.

Remove redundant mis-spelled method

---

app/forms/workbasket_forms/base_form.rb
app/models/measure_type.rb
app/models/measure_type_series.rb

When loading the create measure form the development log is filled with hundreds of database queries, almost all of which are avoided by eager loading the related descriptions for the records which are displayed in the form.
It saves a whole 2.6s rendering time on first uncached load (2710.6ms vs 79ms), across three HTTP requests.
Not only does this improve performance but the primary reason for doing this was to make the log usable for development purposes, as it was previously filled with irrelevant information and I am trying to figure out what is happening currently.

Eager load associated records when displaying create measure form

---

app/interactors/workbasket_interactions/create_measures/settings_saver.rb

This change affects the submission of the second page of the create measures form.
This method call to `validate!` looks innocuous but is actually very expensive to run (it executes dozens of database queries within a transaction which is then rolled back, which takes 2.5 seconds). It's also not used for anything; the output and mutations on the object don't appear to be subsequently used at all.
Additionally, in the [only use case](https://github.com/uktrade/trade-tariff-management/blob/master/app/controllers/workbaskets/base_controller.rb#L87) I can identify the `validate!` method is already called explicitly before `persist!`, meaning the validations are run twice within the same request unnecessarily, which adds an extra 2.5s to an already very long-running request (11.5s total, now …

Remove redundant validate! method call

---

.circleci/config.yml

Due to the current state of the codebase, it is likely that every file will require
a lot of work to be able to pass the linting requirements. This will slow development
down and, with a tight deadline, this is not our current priority so this change
will remove the linting steps from our CI process.

Remove all linting from circleci

---

app/views/shared/vue_templates/_measure_component.html.erb
app/views/shared/vue_templates/_opening_balances_manager.html.erb
app/views/shared/vue_templates/_quota_section.html.erb
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim
app/views/workbaskets/create_quota/steps/main/_order_number_description.html.slim
app/views/workbaskets/shared/steps/main/_measure_type.html.slim
spec/features/workbasket/quota/quota_creation_spec.rb

This PR adds happy path feature test for user creating a quota so that we can begin to
refactor and simplify some of the code surrounding it while being more confident that
we will know if these changes break expected functionality.
I have added attributes to some relevant html elements in order to make selecting them in the
test more transparent and less complicated.
In the test I have abstracted capybara behaviour into methods describing the page on 
which they are performed in an attempt to both make the test easier to understand at 
a glance and make the pinpointing of failing steps easier conceptually.

Add feature test for creating quota

---

app/interactors/workbasket_interactions/settings_saver_base.rb
spec/features/workbasket/quota/quota_creation_spec.rb
spec/interactors/workbasket_interactions/create_quota/settings_saver_spec.rb

Create quota workbasket names are meant to be the description that the user fills in during the create quota process, however they are currently the quota order number that the user fills in.
This PR corrects this bug.

Workbasket name bug

---

app/interactors/workbasket_interactions/settings_saver_base.rb
app/value_objects/workbasket_value_objects/attributes_parser_base.rb
config/locales/en.yml

[https://trello.com/c/nTGqz0f1/644-quota-incorrect-commodity-codes-error]
Expected error: The Create quota page should show ask user to select Origin.
Actual : The Configure Quota page shows an incorrect error asking to fill in commodity code in the previous page (Which has already been filled in).

Fix incorrect error when saving a Quota without a geographical origin.

---

app/interactors/workbasket_interactions/edit_quota/settings_extractor.rb
spec/factories/quota_factory.rb
spec/interactors/workbasket_interactions/edit_quota/settings_extractor_spec.rb

Regardless of the period type we assign to a quota (i.e annual,
quarterly etc) when we go to edit the quota it shows up as
`custom`.
This PR fixes this bug.
I have added an end period date to the quota factory `actual` trait
as without one it quota definition could not be saved and so the
factory does not represent real data without this change.
Note: It looks like the seed data do not have a `workbasket_type_of_quota`
so additional work will need to be done for the existing data.

Fix quota period type bug

---

app/views/shared/vue_templates/_quota_section.html.erb
app/views/workbaskets/create_quota/steps/_conditions_footnotes.html.slim
app/views/workbaskets/create_quota/steps/_review_and_submit.html.slim

Remove sub quota and parent quota views from the create quota workflow
to remove complexity.

Remove sub quota and parent quota views

---

app/models/concerns/workbasket_helpers/settings_base.rb
app/models/workbaskets/bulk_edit_of_quotas_settings.rb
app/models/workbaskets/create_measures_settings.rb
app/models/workbaskets/create_quota_settings.rb
app/models/workbaskets/workbasket.rb
spec/integration/workbaskets/workbasket_spec.rb

When changing status to "Editing" reset all of the 'validation_step_passed', so they need to go through the 'generation' of the measures/quotas/etc. again.

Fix bug caused when status changed to 'editing'

---

app/views/workbaskets/main_menu_parts/_actions.html.slim
spec/features/workbasket/main_menu_spec.rb

Add tests for main menu spec to check for how workbaskets are displayed in different states.
Add back in link for `withdraw/edit` for `awaiting approval` and `rejected` status workbaskets which seems to have got lost in a previous PR.

Crosscheck feature test

---

app/interactors/workbasket_interactions/workflow/cross_check.rb
app/models/workbaskets/workbasket.rb
app/views/shared/vue_templates/_cross_check_decision.html.slim
app/views/workbaskets/main_menu_parts/_actions.html.slim

move baskets straight to 'awaiting_approval' after cross-check
- Fix bug where approvers could not see approval link but non-approvers could. (Wat!)

- No longer use status 'ready_for_approval'

---

app/helpers/workbasket_helper.rb
app/views/workbaskets/main_menu_parts/_actions.html.slim
spec/features/workbasket/main_menu_spec.rb
spec/features/workbasket/quota/quota_spec.rb

Show 'Withdraw/Edit' option on create quota workbaskets from main menu.
Clicking the link allows users to edit and resubmit their quota for cross check.

Allow withdrawing and editing of create quota workbaskets

---

config/initializers/cookies_serializer.rb

We previously used marshal, the accepted standard practise is to use json to serialize cookies.
A brief explanation can be found here: https://www.happybearsoftware.com/almost-protect-yourself-from-cookie-session-store

Serialize cookies with json

---

app/views/workbaskets/events/_sent_to_cds.html.slim

Currently when user clicks to view a workbasket with the status of
`sent_to_cds` they get an error due to the relevant partial not existing
This PR adds a partial view for the `sent_to_cds` event and fixes this
issue.

Add sent_to_cds partial

---

app/services/xml_generation/taric_export.rb
app/services/xml_generation/upload.rb
spec/services/xml_generation/taric_export_spec.rb

We need to upload our data to an S3 bucket in order to pass it over to CDS.
This PR adds the logic to upload to S3 although the file names/bucket names
are just placeholders until we have more information on where we need to
upload the files to in production.

Upload XML to S3

---

app/assets/javascripts/components/find-additional-codes.js
app/assets/javascripts/components/find-measures.js
app/assets/javascripts/components/find-quotas.js
app/controllers/workbaskets/workflows/approves_controller.rb
app/controllers/workbaskets/workflows/cross_checks_controller.rb
app/controllers/workbaskets/workflows/workflow_transitions_controller.rb
app/decorators/workbaskets/workbasket_decorator.rb
app/helpers/workbasket_workflow_helper.rb
app/models/workbaskets/event.rb
app/models/workbaskets/workbasket.rb
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/main_menu_parts/_actions.html.slim
config/locales/en.yml
spec/unit/searches/measures/status_filter_spec.rb

Remove assigning of cross-checker and approver state workbasket events.
https://trello.com/c/w1eRy95L/760-whenever-the-user-enter-the-cross-check-page-a-status-change-entry-is-made-in-the-events-for-the-workbasket-this-leads-to-a-very

Remove state 'ready_for_approval'.

---

app/views/workbaskets/create_measures/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim

Summary pages for measures should display the entered commodity codes, not the filtered codes.
https://trello.com/c/8c91fOrf/761-create-measures-in-summary-pages-display-the-commodity-codes-that-the-user-entered-not-the-filtered-codes

Summary pages for measures should display the entered commodity codes

---

app/interactors/workbasket_interactions/settings_saver_base.rb

Trello card: https://trello.com/c/u2xFT56y/765-on6-conformance-error-on-creating-a-new-quota
ON6 conformance error is getting raised when a user does not fill in the quota periods.
The expected behaviour is that it shows an error that tells the user that they missed filling
in a field and does not show conformance errors until the form is correctly completed.
This PR fixes this bug by only doing conformance checks if the quota period section of the
quota form is filled out and raising general validation errors if it is not.

ON6 bugfix

---

app/assets/stylesheets/components/layout.scss

Sets layout to fixed width 1280px
Sets layout to left of screen
Will remove commented SCSS once we've established the new layout doesn't break anything
Here's what it looks like:

Fixed width layout

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/status_pages/_next_step_links.html.slim
spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb

This change allows users to navigate to the next workbasket they need to cross check or approve
without going back to the main menu first.

Allow navigation to next workbasket in workflow

---

app/value_objects/workbasket_value_objects/attributes_parser_base.rb
app/views/workbaskets/create_measures/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim

Currently if an exception code is entered that is not a leaf node, then the page will show all the leaves instead of the original value entered. This change is made so that pages show the original exception codes entered.

Display the commodity code exceptions that were entered.

---

app/services/xml_generation/download.rb
app/services/xml_generation/upload.rb

Note: This PR needs to be tested in isolation on uat to determine if solution has worked as expected.
Due to us saving XML files in a different path on non dev envs
we need to make some changes to the upload logic.

Fix upload issue in non dev environments

---

app/assets/stylesheets/components/alert.scss
app/views/workbaskets/create_additional_code/_action_links.html.slim
app/views/workbaskets/create_additional_code/_form.html.slim
app/views/workbaskets/create_certificate/_action_links.slim
app/views/workbaskets/create_certificate/_form.html.slim
app/views/workbaskets/create_footnote/_action_links.html.slim
app/views/workbaskets/create_footnote/_form.html.slim
app/views/workbaskets/create_geographical_area/_action_links.html.slim
app/views/workbaskets/create_geographical_area/_form.html.slim
app/views/workbaskets/create_measures/_form.html.slim
app/views/workbaskets/create_quota/_form.html.slim
app/views/workbaskets/shared/_action_links.html.slim

Places 'Progress saved' message under 'Next step' or 'Finish' headings for the following views:
- Create new additional codes
- Create new geographical area
- Create a new footnote
- Create measures
- Create a certificate, license or document
Here's what the new positioning looks like:
Note: 'Create new registration' doesn't have 'Save progress' functionality so ignoring

positive-confirmations-inline

---

app/views/measures/bulks/save_actions_popups/_base.html.slim

Replaces link with GOVUK button in bulk measures save progress confirmation modal.
Turns this:
Into this:
Note: Somehow doubt this is the only confirmation modal in the app, but it's the only one I could find. Will raise further PRs as/when I see more of these.

confirmations-and-modals: bulk measures, save progress modal

---

app/views/workbaskets/create_quota/show.html.slim
app/views/workbaskets/create_quota/steps/_review_and_submit.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_approval_rejected.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_cross_check_rejected.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_quotas.html.slim

Users cannot see the reasons that their quotas have been rejected from
cross-check or approve due to the views that are being rendered in the workflow
process. This PR fixes this issue. (See before and after screenshots below).

Fix bug that stopped users seeing reject reasons

---

app/models/workbaskets/workbasket.rb
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/view/_awaiting_cds_upload_edit.html.slim

Allow approver users to see approved `bulk edit measures` workbaskets in the main menu.
Add awaiting upload status page for these workbaskets.

Add bulk edit measure status pages

---

app/views/shared/_tariff_breadcrumbs.html.erb

(due to the chapters_sections table being empty on the development server)
Not sure if this is likely on a live server, but made the code 'nil-safe' incase the table is empty.
https://trello.com/c/mumT3Fyq/827-check-a-commodity-code-description-link-is-not-working-in-create-measure-form

Fix Exception in Commodity Code Check

---

app/assets/javascripts/vue_components/records-grid.js
app/views/shared/vue_templates/_records_grid.html.erb

Select all functionality is currently unavailable if some of the items
in the search list are locked. This commit allows select all to work for
all but the locked items even when both locked and unlocked items
are shown in the list of items.

Allow select all even if some items are locked

---

app/assets/stylesheets/components/measure_form.scss

Bit of a damp squib, but at least the error summaries now display more like GOVUK than before. This is still not the correct design pattern (the error summary block should contain a list of errors that link to the form elements where the validation has failed -- see https://design-system.service.gov.uk/components/error-summary/).
Also, I could not find an easy way to move the error summary block to the top of the page. In any case, here is what the style update looks like for the error summary:

Applies GDS error summary style

---

app/assets/stylesheets/components/additional-codes.scss
app/assets/stylesheets/components/button-dropdown.scss
app/assets/stylesheets/components/find-items.scss
app/assets/stylesheets/components/forms.scss

Changes keylines to 1px 'height'
Changed ParsleyJS error summary border width to match GOVUK (was 3px, is now 5px)

Horizontal keyline fixes

---

app/assets/stylesheets/components/create-measures.scss

Sets table width to 640px (50% of 1280px)

Create measures details table width correction

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/panels.scss

Brings 'Origin mechanic' styling closer to design reference*:
https://uktrade.atlassian.net/wiki/spaces/TARIFFSALPHA/pages/621346929/Mechanic+-+Origin+s+Selector
This is what this looks like:

Adjust vertical spacings

---

app/controllers/xml_generation/exports_controller.rb
app/models/workbaskets/workbasket.rb

We have an issue whereby the uploading of an edit measure workbasket is not
allowed despite it being approved. This is because it has a slightly different status,
i.e `awaiting_cds_upload_edit` rather than the expected `awaiting_cds_upload_create_new`.
This commit allows workbaskets with either of these statuses to be uploaded.

Allow upload xml from edit measures workbaskets

---

app/services/measure_service/fetch_measure_sids.rb

Users currently experience a bug when selecting measures which means that all measures
(even those which are locked) are selected when they tick the `select all` checkbox.
This commit fixes this issue. It changes all_measure_sids to unlocked_measure_sids meaning
that locked measures can never be selected.
Note: measure_sids need to be integers in order to subtract them from the unlocked_measure_sids
hence them being mapped to integer.

Fix select all bug

---

app/helpers/application_helper.rb
spec/features/version_identifier_spec.rb

Prior to this change, the commit sha was always shown
This change will display a tag if found or fallback to the commit sha
https://trello.com/c/znxn2sf4/825-ensure-gitcommit-environment-variable-is-used-in-healthcheck-response

feat: display semantic version in footer

---

app/controllers/admin/workbasket_status_controller.rb
app/interactors/workbasket_interactions/workflow/approve.rb
app/interactors/workbasket_interactions/workflow/cross_check.rb
app/models/workbaskets/workbasket.rb

Prior to this change, when a workbasket status was changed when going through cross-check, approval or via the tester backdoor only the workbaskets status was changed but the underlying items within the workbasket did not have their status changed.
This change adds a number of methods which handle the changing of status of both the workbasket
and the objects within the workbasket to the workbasket class in order to fix this issue.
Trello card: https://trello.com/c/Ru6wqaw3/848-search-status-not-updated

Fix status change bug

---

app/assets/stylesheets/components/panels.scss

Fix: confirmation panel styling
Prior to this change, confirmation panels had insufficient padding
This change allows .panel--confirmation class to override existing padding
This is what it looked like:
This is what the fix looks like:

Fix: Confirmation panel styling

---

app/assets/stylesheets/components/measure-components.scss

Prior to this change, the 'Add another duty expression' links were separated by keylines, which are not part of the design spec
This change adds SCSS styling so that the keyline only appears under the last duty expression link
This is what it looks like:
I almost gave up trying to coax the JS+Slim to behave as intended in the design. Then, in a moment of glorious inter-dimensional 3rd eye awakening, I realised it could be done with a few lines of CSS.

'Add another duty expression' link above keyline

---

app/assets/stylesheets/components/find-items.scss

Prior to this change, wide tables had columns that could not be viewed
This change allows table scrolling so that clipped columns are viewable

Fix: If applied, this commit will make tables scroll

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/view/_cds_error.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_cds_error.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/events/_cds_error.html.slim
app/views/workbaskets/events/_published.html.slim

Prior to this change, the app would crash when viewing a workbasket that
has a status of `published` or `cds_error`.
This change adds the appropriate view for a `published` or `cds_error` workbasket that is
needed to prevent the crash.
Trello card: https://trello.com/c/LzOXuABS/862-clicking-on-view-on-a-published-workbasket-crashes

Fix: Prevent app crash when viewing published workbaskets

---

app/services/xml_generation/download.rb

Prior to this change, the download job returned an array of xml strings.
This makes it difficult to identify which file is a mainfile and which is a
metadata file.
This change returns a hash of filename/xml string pairs to make it
easy to identify which file is which.

Fix: Return XML strings in hash

---

app/views/workbaskets/bulk_edit_of_measures/show.html.slim
app/views/workbaskets/create_geographical_area/show.html.slim
app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/show.html.slim

Prior to this change, when viewing a rejected workbasket the link to
edit on the show page did not ask for confirmation before withdrawing
This change now requires a confirmation message before withdrawing
and allowing editing.
https://trello.com/c/nMQVP7xn/843-withdraw-workbasket

Fix: add confirmation message for withdrawal

---

app/models/workbaskets/workbasket.rb
app/views/workbaskets/create_quota/show.html.slim

Prior to this change, if a workbasket is rejected from approval or cross
check it does not show why it was rejected.
This change fixes this issue by stopping multiple events being created
after cross-check or approval. The reason that the rejection reason is not
showing is because we were creating 2 events everytime we reject or approve
a workbasket.
The first event has the rejection reason included but the second
does not and is overriding the first when shown on page. This commit
stops 2 calls to `move_status_to!` for every reject or approve.
It also has a side benefit of cleaning up the event history.
Trello card: https://trello.com/c/yHV2NLL0/819-submitter-cannot-see-the-the-approval-rejected-reason-for-quota

Fix: Rejection reason not showing up

---

app/assets/stylesheets/components/additional-code-show-page.scss

The table heading and body had incorrect column widths
This change applies correct column widths, in line with the quotas table styling.
Before:
After:

Fix: 'Additional code' table layout

---

app/views/workbaskets/create_quota/steps/_review_and_submit.html.slim

Prior to this change, the create quota review and submit page displayed
the quota periods twice
This change removes one of the quota periods.
https://trello.com/c/saGQODtx/868-review-and-submit-page-of-quota-creation-is-showing-two-identical-quota-periods-instead-of-one-with-one-measure-created

Fix: remove double display of quota periods

---

app/assets/stylesheets/components/create-measures.scss

Details table display was previously limited to 640px width
This change removes this restriction, and adds horizontal scrolling
In reference to https://trello.com/c/dDBNxe1O/800-table-cropping-glitch-on-view-measures-workbasket
Before:
After:

Fix: Applies full width to details table display

---

app/models/workbaskets/workbasket.rb

Prior to this change, if we tried to edit a published ite, and at some
point during the process withdrew the workbasket then the published
item would be deleted from our application.
This change stops the `cleaning up` of temporary data. The issue arises
from the fact that both the new item (i.e measure or quota) and the published
one are both `cleaned up`.
This change removes this step from the edit process.
Note: This will mean that both the new and the published items will
stay in an editing state and be locked on the search page until the user
makes the necessary changes.
Trello card: https://trello.com/c/I92IttdN/872-historical-measure-quota-gets-deleted-wrongly

Fix: Accidental deleting of published workbaskets during editing

---

app/assets/stylesheets/components/tables.scss

There are too many columns to fit in the current max-width of 1700px
This change adds 100px width to fit all columns
This change does not relate directly to any Trello ticket, however, it is broadly part of https://trello.com/c/kbLZ7DMa/755-tables
Before:
After:

Fix: Bulk edit measures bulk action table

---

app/interactors/workbasket_interactions/settings_saver_base.rb

Prior to this change, user didn't need to enter a description. The
workbasket would be created but fails to display in the list.
This change does not allow the workbasket to be created until there is
a description.
https://trello.com/c/lux0F6An/839-creating-quota-without-work-basket-name-gets-created-in-the-database-but-dont-show-up-in-the-work-basket-of-as-submitter-or-the

Fix: Make Quota Description mandatory field

---

config/environments/production.rb

Prior to this change, we are not getting full error messages on prod
This change adjusts the setting config.consider_all_requests_local to
see if we can get more informative errors. This should be reverted
before live.
https://trello.com/c/TKQh7QiK/875-for-trail-testing-to-try-and-understand-the-502-error-we-have-changed-a-setting-in-production

TST: Trial error setting in prod environment

---

app/views/quotas/quotas/_search_page.html.slim

Prior to this change, when searching for a quota the user could not
see the number of results returned.
This change shows the user the number of quotas that meet the search
requirements.
Trello card: https://trello.com/c/UXT81ffC/871-quota-search-bug-not-showing-the-number-of-search-results

Fix: Quota search results total not showing

---

app/views/workbaskets/shared/steps/main/_measure_type.html.slim

Measures type select control default value was being clipped out of view
This change provides more space in the view layout to render the default value in full
Trello: https://trello.com/c/PEdodUIi/756-styling-of-form-controls
Before:
After:

Fix: increases width of measure type select control

---

app/assets/stylesheets/components/select.scss

Rounded corners provide a subtle cue to differentiate against similar-looking typeahead
This fix targets selectize-input rendered with 'has-options' class (typeahead doesn't use this class)
**Note:** Border radius (rounding) pixel value has been approximated 'by eye' as the value is not specified in the UX design reference.
Trello: https://trello.com/c/PEdodUIi/756-styling-of-form-controls
Before(s):
After(s):

Fix: Renders dropdowns with rounded corners

---

app/value_objects/workbasket_value_objects/create_measures/attributes_parser.rb
app/views/workbaskets/create_measures/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_details.html.slim

Fix: Tweak info on `Review and Submit` page
Prior to this change, we had some unhelpful or unnecessary info on
the review and submit measures/quotas pagse.
This change removes operation date, which we no longer use, and adds
the  type id to the measure type field in the details table in order to
help users more easily understand which type they selected.
Trello card: https://trello.com/c/ZDkum6VE/863-update-review-submit-summary-information

Fix: Tweak info on Review and Submit page

---

config/environments/production.rb

Prior to this change, we trialled a setting to see if we cna get better
error messages for the 502 error we sometimes get on production.
Error meesages were no different so reverting this back to false.
This change removes the 'consider_all_requests_local' setting.
https://trello.com/c/TKQh7QiK/875-for-trail-testing-to-try-and-understand-the-502-error-we-have-changed-a-setting-in-production

TST: Revert 94b3a315 - error reporting setting

---

app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/show.html.slim

Prior to this change, when viewing a `create measure` or `create quota`
workbasket with the status of `awaiting_cross_check` there was no link to
exit to the main menu
This change adds `exit to main menu` link to above pages.
trello card: https://trello.com/c/66LReGRc/851-some-view-page-doesnt-have-the-exit-link

Fix: Add exit to main menu links to view measure/quota

---

app/value_objects/workbasket_value_objects/shared/commodity_codes_analyzer.rb

Prior to this change, a blank start date when creating a measure caused an exception.
This change defaults the start date to today's date for the purpose of checking for valid commodity codes.
https://trello.com/c/nLOYvMnv/396-dit-tq-54-changes-to-validation-and-conformance-error-handling-40

Fix: blank start date causing infinite spinning.

---

app/interactors/workbasket_interactions/create_measures/settings_saver.rb

Prior to this change, would not see an accurate error if they tried to create a measure
without a regulation id, origin or measure type.
This change raises an error if any of these fields are missing 
Trello card: https://trello.com/c/fHudEr8Y/830-wrong-error-message-please-review-the-following-errors-general-goods-commodity-codes-can-be-empty-but-only-if-one-or-more-meursi

Fix: This commit adds missing validations on create measure

---

app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim

Prior to this change, viewing a Quota with status 'Awaiting Approval'
caused an exception and error message displayed
This change adds the missing partial.
https://trello.com/c/VmZMhVYL/740-tq-206-clicking-on-the-review-for-cross-check-on-the-workbasket-type-create-quota-is-leading-to-error-were-sorry-but-something-w

Fix: View quota 'awaiting approval' error

---

app/helpers/application_helper.rb
spec/features/version_identifier_spec.rb

Prior to this change, it was assumed the new env var to hold the git
tag would be called GIT_TAG, but it was created as GIT_BRANCH
This change uses the correct env var name GIT_BRANCH
https://trello.com/c/znxn2sf4/825-ensure-gitcommit-environment-variable-is-used-in-healthcheck-response

Fix: correct env variable name GIT_BRANCH

---

app/interactors/workbasket_interactions/settings_saver_base.rb
app/views/workbaskets/create_quota/steps/_main.html.slim
spec/features/workbasket/quota/quota_creation_validations_spec.rb
spec/features/workbasket/quota/quota_spec.rb

Prior to this change, the user had to specify an operation date when
creating a quota, however this operation date is not necessary.
This change removes the need for an operation date to be specified to
create a quota and removes the section of the form relating to it.
Trello: https://trello.com/c/BEusDZPW/881-create-quota-operation-date

Fix: This commit removes operation date from create quota form

---

app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, we showed operation date in the quota summar of
configuration. We should instead be using start date as operation date
is no longer relevant.
This change switches operation date for start date.
trello card: https://trello.com/c/ZDkum6VE/863-update-review-submit-summary-information

Fix: Show start date instead of operation date in quota summary

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/status_pages/_next_step_links.html.slim

Prior to this change, after cross-check of a bulk edit measures workbasket the 'view' workbasket link on the cross check summary page would not load the measures table
This change corrects the link and displays the measures grid
https://trello.com/c/RoexEncG/854-view-measures-work-basket-is-loading-and-not-displayed-any-measures-on-the-cross-checkers-confirmation-pagevia-view-these-measur

Fix: after cross-check, allow view of bulk edit workbasket

---

app/assets/stylesheets/components/tables.scss

The sorting arrow icon was overlapping with adjacent table headings
This change adjusts table column widths to make room for the sorting arrow icon
Trello link:
https://trello.com/c/nayAOWQ6/869-table-heading-columns-not-lining-up-well-on-bulk-edit-measures-page
Before/after:

Fix: Table column withds adjusted for 'sort' arrow

---

app/assets/stylesheets/components/select.scss

Previously content was overlapping in the 'unit of measure' drop down
This change separates content to avoid overlap
Trello link: https://trello.com/c/dDBNxe1O/800-table-cropping-glitch-on-view-measures-workbasket
Before:
After:

Fix: better separation between drop down columns

---

app/views/workbaskets/create_quota/show.html.slim

Prior to this change, when viewing a create quota workbasket there was
a link to find measures rather than find quotas.
This change replaces the measures link with a quota link
Trello card: https://trello.com/c/fYViqFty/882-incorrect-quota-link

Fix: Correct link on quota page

---

app/interactors/workbasket_interactions/settings_saver_base.rb
app/services/dates_service.rb
spec/services/dates_service_spec.rb

Prior to this change, a user could create a quota with custom periods
that overlapped and no error was raised.
This change checks for overlaps in the dates and raises an error if it finds one.
Trello card: https://trello.com/c/Jg5oJb5t/880-quota-period-should-not-overlap-with-date-selector

Fix: Add validation around date overlap in create quota

---

app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/main_menu_parts/_actions.html.slim

Prior to this change, we had links to schedule and reschedule export
to cds despite no longer exporting on a schedule.
This change removes links to schedule exports to cds.
Trello: https://trello.com/c/XyVTXwIQ/888-remove-reschedule-export-to-cds-feature

Fix: Remove reference to scheduling export to cds

---

app/interactors/workbasket_interactions/settings_saver_base.rb

Prior to this change, users could tick the box that indicates that the quota
has a license but could create a quota without errors without specifying the
quota.
This change raises an error if no quota is specified after user has
ticked the `quota is licensed` checkbox.
Trello card: https://trello.com/c/WHEx43aN/883-validation-failed-for-is-this-a-licensed-quota-check-box-is-checked-without-selecting-the-licence-from-drop-down

Fix: Validate presence of license if quota is licensed

---

app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_sent_to_cds.html.slim

Prior to this change, it would throw an exception.
This change adds a partial that matched the sent_to_cds status.
https://trello.com/c/2Fssk309/886-view-quota-page-crashed

Fix: display quota correctly when status is sent_to_cds

---

app/views/shared/vue_templates/_condition.html.erb

Prior to this change, the change conditions popup for bulk edit measures did not populate the certificate type and id.
This change uses the correct field and prepopulates the fields.
https://trello.com/c/k3D7Wc21/794-certificate-type-and-id-not-pre-populated-when-editing-measure-conditions

Fix: pre-populate fields in bulk edit pop up

---

config/environments/production.rb

Prior to this change, production could not compile assets due to smart quotes being used.
This change replaces the smart quotes with normal quotes.

Fix: replace 'smart quotes' with normal quotes

---

app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, when cross checking a new measure, the user
could only see the description of the measure type, not the number.
This commit displays the measure type number.
Trello card: https://trello.com/c/PIlwmkkw/501-dit-tq-43-edit-measures-multiple-issues-regulation-selection-regulation-assignment-measure-id-and-date-display-no-xml-no-justifi

Fix: Shows measure type number to cross check and approver

---

app/interactors/workbasket_interactions/create_measures/settings_saver.rb

Prior to this change, ME9 conformance error would be raised if we were didn't
enter some of the mandatory fields. It should only be raised once all mandatory
fields are completed.
This change only raises the ME9 error if there are no existing validation errors.
Trello card: https://trello.com/c/fHudEr8Y/830-wrong-error-message-please-review-the-following-errors-general-goods-commodity-codes-can-be-empty-but-only-if-one-or-more-meursi

Fix: Commodity code error showing out of turn

---

Gemfile
Gemfile.lock
spec/rails_helper.rb
spec/support/capybara.rb

Prior to this change, updates of chrome caused test failures
This change replaces chromedriver-helper with webdrivers gem. And also updates some of the testing gems.

Fix: chromedriver-helper gem is no longer supported

---

app/assets/javascripts/application.js

Auto-scrolling was previously implemented but is hit and miss, or doesn't work at all
This change resolves the issue by waiting for the page to load, and scrolling to the results table or the results loading section, whichever is present.

Fix: Scrolls to search results

---

app/views/workbaskets/create_quota/submitted_for_cross_check.html.slim

Prior to this change, the withdraw/edit quota link was not implemented it.
This change implements it.
Trello: https://trello.com/c/4GAZ6v8F/890-withdraw-edit-quota-link-needs-to-be-updated

Fix: Makes withdraw quota link work

---

app/assets/javascripts/application.js

Previous implementation used a timer to wait a fixed number of seconds
This approach fails whenever the page takes longer to load than the prescribed time
This change resets the timer periodically (every 500ms), allowing the auto-scroll functionality to wait indefinitely until there are search results to scroll to. Recursion FTW!
Before/After screen shots: none

Fix: auto scroll page to search results

---

app/views/shared/vue_templates/_condition.html.erb

Prior to this change, conditions without a certificate would not show
in editing pop up.
This change does not try to populate certificate fields if there is no
certificate.
Trello card: https://trello.com/c/k3D7Wc21/794-certificate-type-and-id-not-pre-populated-when-editing-measure-conditions

Fix: Show all conditions available to edit

---

app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/view/_editing.html.slim
app/views/workbaskets/create_quota/show.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/view/_editing.html.slim

Prior to this change, if user withdrew a create quota or create measure
workbasket, then clicked the back button, then clicked view to inspect the
workbasket the page would crash.
This change redirects the user to the editing page if the status of
a workbasket is 'editing' even if the user has gone back a page.
Trello card: https://trello.com/c/upz1iBzA/845-back-button-not-refreshing-causing-page-to-crash

Fix: Clicking back after withdraw/edit bug

---

app/assets/javascripts/vue_components/change-conditions-popup.js

Prior to this change, users trying to edit measures by changing conditions
would not be able to.
This change allows users to do this.
Trello card: https://trello.com/c/3iSvx6lC/876-bulk-edit-measure-with-change-conditions-light-box-popup-with-changing-conditions-update-selected-measures-button-is-not-working

Fix: If applied, will allow edit of measure conditions

---

app/helpers/cross_check_helper.rb
app/views/workbaskets/shared/steps/review_and_submit/_bulk_edit_measures.html.slim
app/views/workbaskets/workflows/approves/new.html.slim
app/views/workbaskets/workflows/cross_checks/new.html.slim

Prior to this change, the details had been removed as some types had not
had the section complete.
This change reinstates the details section and removes some duplication.
https://trello.com/c/Rn8FtExt/898-cross-check-and-approval-are-not-showing-the-basket-details

Fix: Reinstate the workbasket details for approval/cc

---

config/environments/development.rb

Front-end developers are unable to attribute runtime errors to the JS source code via the web browser console
This configuration change produces JS assets such that runtime errors can be attributed to the JS source code
Trello link: N/A
Before:
After:

Fix: sets assets debug flag to true

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/ie11.scss

Date picker icon is rendered tiny in IE11
This change applies IE11-specific styles to render the date picker icon correctly
Trello link: https://trello.com/c/X545cirN/907-ie11-browser-compatibility-issues (issue 7)
**NOTE** https://github.com/uktrade/trade-tariff-management/pull/199 merge to master required in order to test this PR.
Before:
After:

Fix: increases size of date picker icon in IE11

---

app/interactors/workbasket_interactions/create_additional_code/settings_saver.rb

Prior to this change, you could submit a workbasket without any new codes
This change checks that there is at least one code in the basket.
https://trello.com/c/1fkycOPj/464-dit-additional-codes-create-new-additional-codes-53

Fix: Prevent submitting empty Additional Codes basket

---

app/assets/javascripts/vue_components/components-coordinator.js
app/assets/javascripts/vue_components/conditions-coordinator.js
app/assets/javascripts/vue_components/custom-select.js
app/assets/javascripts/vue_components/measure-components.js
app/views/shared/vue_templates/_measure_component.html.erb
app/views/shared/vue_templates/_measure_condition_component.html.erb
app/views/shared/vue_templates/_selectize.html.slim
app/views/workbaskets/create_measures/steps/_duties_conditions_footnotes.html.slim
app/views/workbaskets/create_measures/steps/duties_conditions_footnotes/_duty_expression.html.slim
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_conditions.html.slim

This PR disables the duty expression fields if duties already expressed
in conditions.
Trello: https://trello.com/c/sOyrFqSj/768-need-to-swap-order-of-duty-expression-and-conditions-mechanics-in-create-measure

Fix: Disabled adding duties if already specified in condition

---

app/views/workbaskets/create_additional_code/steps/main/_additional_codes.html.slim

IE11 does not support use of template literals (a.k.a ` character)
This change removes template literal in 'Create new additional codes' template, and uses plain old string concatenation instead.
Trello link: https://trello.com/c/X545cirN/907-ie11-browser-compatibility-issues (issue 15)
Before: the 'Create new additional codes' form was not displayed in IE11
After: the 'Create new additional codes' form is displayed in IE11

Fix: Replaces template literals in 'Create new additional codes' view for IE11

---

app/views/shared/vue_templates/_quota_section.html.erb

The view template uses JS template literals, which are not supported in IE11
This change replaces template literals with string concatenation for IE11
Trello link: https://trello.com/c/X545cirN/907-ie11-browser-compatibility-issues (issue 19)
Before: The form in the 'Create quota' view did not display in IE11
After: The form in the 'Create quota' view does display in IE11

Fix: 'Create quota' view template compatibility with IE11

---

app/assets/stylesheets/ie11.scss

Drop down options are clipped if the option is wider than 138px
This change changes the styling to allow the browser to determine the correct length (auto)
Trello link: https://trello.com/c/WAcSDTnN/909-ie11-drop-down-menu-options-cropped
Before (IE11):
After (IE11):

Fix: Drop-down options un-clipped in IE11

---

app/assets/javascripts/components/additional-codes-show-page.js
app/views/shared/vue_templates/_records_grid.html.erb
app/views/workbaskets/create_additional_code/show.html.slim

Prior to this change, the display of Additional Codes had some missing
fields and also had some unnecessary columns.
This change fixes:
- the display-grid was not hiding the select column correctly
- description was not displaying
- removes the status column as it's already displayed above
https://trello.com/c/nBormaKh/806-view-certificate-data-missing-display-glitches

Fix: Additional Code display glitches

---

app/views/workbaskets/create_additional_code/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_approval_rejected.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_cds_error.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_cross_check_rejected.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_ready_for_export.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_sent_to_cds.html.slim

Prior to this change, the view page did not show top notification,
withdraw from workflow button and the correct status changes
This change adds those parts of the view page.
https://trello.com/c/WgBplkgT/910-additional-codes-submitted-for-cross-check-do-not-have-description-and-submitted-for-cross-check-in-details

Fix: update display of Additional Codes basket

---

app/interactors/workbasket_interactions/create_additional_code/settings_saver.rb

Prior to this change, You could create 2 identical Additional Codes in a workbasket
This change checks the basket for duplicates.
https://trello.com/c/vVUslwBT/911-we-can-create-same-additional-codes-with-same-type-and-code-and-description-no-errors-displayed

Fix: prevent duplicate Additional Codes in basket

---

app/interactors/workbasket_interactions/create_geographical_area/settings_saver.rb
spec/features/workbasket/geographical_area/geographical_area_creation_spec.rb

New: Add group membership functionality
Prior to this change, we could not persist group memberships in our database.
The UI would make it look like the membership functionality was executed
successfully but it was not.
This change persists group memberships.
Trello card: https://trello.com/c/OGda243E/906-investigate-assigning-geographical-area-memberships

Add geo memberships

---

.gitignore
CONTRIBUTING.md
app/assets/javascripts/components/duty-expression-formatter.js
app/views/shared/vue_templates/_bulk_edit_records.html.erb
git_commit_msg.txt

Prior to this change, there was a bug in the frontend at duty
expressions formatter which resulted to some duties not to be displayed.
Further more I have extended the abbreviation formatter logic to render
`MAX`. A bug related to the story still exists in the BE or it is a
data issue.
Ameneded duty-expression-formatter.js file
See: (TARIFFS-117)[https://uktrade.atlassian.net/browse/TARIFFS-117]

Fix: Display of complex duty expressions

---

app/interactors/workbasket_interactions/create_geographical_area/settings_saver.rb
app/views/shared/vue_templates/_add_geo_areas_to_group_popup.html.slim
spec/features/workbasket/geographical_area/geographical_area_creation_spec.rb

Prior to this change, we could not persist group memberships in our database.
The UI would make it look like the membership functionality was executed
successfully but it was not.
This change persists group memberships.
Card: https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-59

New: Add geo group with country

---

app/assets/javascripts/components/workbaskets/create_geographical_area.js
app/views/workbaskets/create_geographical_area/steps/main/_memberships.html.slim
spec/features/workbasket/geographical_area/geographical_area_creation_spec.rb

Prior to this change, there was no way for a user to create a country that
is not part of the default groups.
This change allows users to do this.
Jira: https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-46

New: Allow removing of default groups when creating a country

---

app/models/additional_code.rb
spec/models/additional_code_spec.rb

Prior to this change, the Additional Code will display the description
based on it's validaity dates compared to the current time. So when
examining a new code in the future it would not display the correct
description.
This change retrieves the correct description by setting time machine to
use the validity start date of the additionanl code and retrieve the
last one it finds.
https://uktrade.atlassian.net/browse/TARIFFS-60

Fix: Display correct Additional Code description

---

app/assets/javascripts/components/validators/additional_codes.js

Prior to this change, if an error message was containing a special
character such as '+' then only part of string was returned.
This change fixes the match patern logic to include any character
See: [TARIFFS-74](https://uktrade.atlassian.net/browse/TARIFFS-74)
After:

Fix bug on displaying full server error messages

---

app/views/layouts/application.html.erb
app/views/layouts/govuk_template.html.erb
app/views/workbaskets/edit_geographical_area/steps/main/_code.html.slim
app/views/workbaskets/edit_geographical_area/steps/main/_type.html.slim

Prior to this change, there were some copy glitches on edit geographical
area.
This change just disables the input field instead of whole section and
also closes the single quote in the correct place. Also fixes a core
layout bug with flash container messing html layout
See [Trello](https://trello.com/c/MZhaDSJL/815-copy-glitches-on-edit-geographical-area)
See [TARIFFS-69](https://uktrade.atlassian.net/browse/TARIFFS-69)
**After:**

Fix copy glitches on Edit Geographical Area

---

app/interactors/workbasket_interactions/create_geographical_area/settings_saver.rb

Prior to this change, the memberships were not showing when
generating XML for a create geographical area group.
This change adds workbasket id to the geographical area membership
which allows the XML generation process to add in the membership data
to the XML.
Card: https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-198

Fix: Show geo area memberships in XML

---

app/interactors/workbasket_interactions/create_geographical_area/initial_validator.rb

Prior to this change, a user could enter a lowercase area id when creating
a geographical area. This causes errors when we generate XML as it is not
conformant with the schema
This change ensures that the user enters an upper case geographical area.

Fix: Raise error if user does not use upper case area id

---

app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/view/_published.slim

Prior to this change, Exception was thrown when viewing a published workbasket for Additional Codes.
This change adds the missing partial.
https://uktrade.atlassian.net/browse/TARIFFS-75

Fix: couldn't view published basket with Additional Code

---

db/migrate/20190603135337_replace_all_additional_codes_view.rb
db/structure.sql

Prior to this change, the view all_additional_code would return
all historical discriptions for a code.
This change limits the search to just the latest description.
https://uktrade.atlassian.net/browse/TARIFFS-194

Fix: searches for Additional Codes

---

app/assets/javascripts/components/workbaskets/edit-geographical-area.js
app/models/workbaskets/edit_geographical_area_settings.rb
app/views/workbaskets/edit_geographical_area/edit.html.slim

Prior to this change, memberships are not being displayed
when we go to edit an existing geographical area and there
is no way to add or remove memberships.
This change allows the user to view memberships and view
the memberships that they are adding or removing in the ui.
Note: This is a front end fix only. Users cannot successfully submit
these changes. Commits to follow to add that functionality.

Fix: Add/Remove memberships in geo area frontend

---

app/controllers/additional_codes/additional_code_types_controller.rb

Prior to this change, user was unable to use drop down to search and
select an additional code
This change fixes a bug on BE select query
See: [TARIFFS-237](https://uktrade.atlassian.net/browse/TARIFFS-237)
**Before:**
**After**

Fix: Additional code dropdown

---

app/assets/javascripts/components/workbaskets/edit-geographical-area.js
app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb
app/models/geographical_area.rb
app/models/geographical_area_membership.rb
app/models/workbaskets/edit_geographical_area_settings.rb

Prior to this change, when a user edited geographical area memberships
via edit geo area the results were not being persisted and processed by
our backend.
This change adds this functionality.

New: Allow persisting of edited geo area memberships

---

app/models/meursing_additional_code.rb
app/views/workbaskets/create_additional_code/steps/review_and_submit/_additional_codes_details.html.slim

Prior to this change, when creating a new additional code that was a
meursing type, their was an exception as the Meursing Additional Code
did not have a description or code type id
This change adds a blank description
https://uktrade.atlassian.net/browse/TARIFFS-75

Fix: Error when displaying Meursing Additional Code

---

app/decorators/geographical_area_decorator.rb
app/views/workbaskets/create_geographical_area/steps/review_and_submit/_geographical_areas.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/_area_details.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_approval_rejected.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_ready_for_export.html.slim

Prior to this change, when reviewing geographical area related
workbaskets the approver/cross checker could not see membership
details.
This change shows these details to reviewers.

Fix: Show membership details to reviewers

---

app/assets/stylesheets/components/layout.scss
app/assets/stylesheets/components/panels.scss
app/assets/stylesheets/components/search-input.scss
app/controllers/nomenclature/sections_controller.rb
app/views/layouts/govuk_template.html.erb
app/views/nomenclature/_sections.erb
config/routes.rb

Prior to this change, a page did not exist for listig
nomenclature sections
This change adds the route and the view for displaying nomenclature
sections
**AFTER**

New: Show nomenclature sections

---

app/controllers/nomenclature/section_chapters_controller.rb
app/views/nomenclature/_section_chapters.erb
app/views/nomenclature/_sections.erb
app/views/nomenclature/_sections_header.erb
config/routes.rb

Prior to this change, a page did not exist for listig
nomenclature section chapters
This change adds the route and a mocked view for displaying
nomenclature section chapters
Front end first iteration work for: [TARIFFS-209](https://uktrade.atlassian.net/browse/TARIFFS-209)
**After:**

New: Frontend work for nomenclature chapters page

---

app/assets/javascripts/components/workbaskets/edit-geographical-area.js

Prior to this change, operation date did not have a default value.
This change gives a default operation date.

Fix: Default geo area operation date to today

---

app/views/workbaskets/create_additional_code/workflow_screens_parts/status_pages/_approval_rejected.html.slim

Prior to this change, an exception was thrown due to missing partial.
This change added the partial
https://uktrade.atlassian.net/browse/TARIFFS-230

Fix: rejecting an additional code Approval caused exception

---

app/interactors/workbasket_interactions/edit_geographical_area/initial_validator.rb

Prior to this change, we would get errors when checking memberships
as sometimes an area did not have a nested geographical area id
This change prevents these errors.

Fix: Bug in membership validation

---

app/assets/javascripts/components/find-additional-codes.js

Prior to this change, if the search results did not have an ordering set by clicking a column then viewing page 2 (or any other pages) threw an exception.
This change the column ordering parameters are only added to the url if an ordering has been specified.
https://uktrade.atlassian.net/browse/TARIFFS-240

Fix: view page 2 of additional code search results

---

app/models/workbaskets/edit_geographical_area_settings.rb

Prior to this change, the start and end dates of memberships were showing
the full date and time. This is confusing for users
This change changes the format of start and end dates of memberships to be
rfc822.

Fix: Correct time format for start and end dates of memberships

---

app/assets/javascripts/vue_components/components-coordinator.js

Prior to this change, a syntax error was preventing any duty expressions being displayed.
This change fixes the syntax.

Fix: JS error when displaying components in measure

---

app/views/workbaskets/edit_geographical_area/steps/main/_type.html.slim

Prior to this change, a user could select to orphan a group, i.e
leave it with no parent group but still be given the option to select
a parent group which makes no sense
This change removes the dropdown from which a user can select
a parent group if they choose to orphan the group they are editing.

Fix: Do not show parent group dropdown if select to orphan

---

app/assets/javascripts/vue_components/additional_codes/change-validity-period.js

Prior to this change, the code was comparing a date against a time, so if tomorrow's date was used as the start date it would throw an error that's it's not in the future as it was less than 24 hours away.
This change sets todaysDate to be a date instead of a datetime. So we are comparing like to like (i.e. now comparing date to date instead of to a datetime).
https://uktrade.atlassian.net/browse/TARIFFS-250

Fix: miscalculating if date in future, for validity period.

---

app/assets/javascripts/vue_components/edit-geographical-area-membership-popup.js
app/views/shared/vue_templates/_edit_geographical_area_membership_popup.html.slim

Prior to this change, there was a delete membership checkbox within
the add membership popup for geographical areas. This is not used as
there is a more obvious way to delete memberships.
This change removes the unused checkbox.
Jira card: https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-51

Fix: Delete membership box

---

app/interactors/workbasket_interactions/create_geographical_area/initial_validator.rb
app/interactors/workbasket_interactions/edit_geographical_area/initial_validator.rb

Prior to this change, a user would receive an unhelpful server
error when trying to create/edit a geo area with an incorrect date.
This change raises an error showing which date field they have
entered an invalid date into.

Fix: Invalid dates raising incorrect error on create/edit geo area

---

app/decorators/geographical_area_decorator.rb

Prior to this change, description, valid from and valid to info was
missing from the view geo area screen if the operation date was in
the future.
This change shows the description info even if the operation date is
in the future.

Fix: Data is missing from view geo area screen

---

app/helpers/workbasket_helper.rb
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/_actions_allowed.html.slim

Prior to this change, there was not a link on the homepage to
withdraw a geo area workbasket from
This change adds the withdraw link to allow users to withdraw
geo area workbaskets from workflow.

Fix: No link to withdraw geo area

---

app/views/workbaskets/create_additional_code/submitted_for_cross_check.html.slim

Prior to this change, on the review page of create additional code
there was a 'withdraw/edit' link that did not work.
This change fixes this broken link.

Fix: Add withdraw additional code link

---

app/value_objects/workbasket_value_objects/create_regulation/attributes_parser.rb

Prior to this change, on the review and submit page for a newly
created regulation the description and the url would be displayed
the incorrect way around.
This change fixes the indexes of the data to show the data in the
correct place for the end user.

Fix: Regulation description and URL mixed up

---

app/assets/javascripts/components/duty-expression-formatter.js

Prior to this change, when user was bulk editing duties, monetary units
where not visible for some cases eg Amount
This change fixes the bug that was preventing unit from being displayed.
See: [TARIFFS-117](https://uktrade.atlassian.net/browse/TARIFFS-117)
**Before:**
**After:**

Fix: Display monetary unit on duties

---

app/interactors/workbasket_interactions/edit_geographical_area/initial_validator.rb

Prior to this change, groups could add another geo area group
as a member.
This change stops this bug occuring by checking for "1" as well as
"group" as the value of geographical_code.

Fix: Groups adding other groups as members

---

app/views/workbaskets/create_geographical_area/steps/review_and_submit/_geographical_areas.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_published.html.slim

Prior to this change, if a create or edit geo area was published, when
the user goes to view it the user gets an error screen.
This change adds the necessary view so that the app will not get an error.

Fix: Create and edit geo areas crashing when viewing published wb

---

app/views/workbaskets/edit_geographical_area/steps/main/_type.html.slim

Fix: If applied this commit will fix the disabled radio buttons issue
Prior to this change, radio buttons were not disabled but just gray
out.
This change adds the disabled attribute to form elements
See: [TARIFFS-251](https://uktrade.atlassian.net/browse/TARIFFS-251)

Fix: If applied this commit will fix the disabled

---

app/views/workbaskets/create_additional_code/steps/review_and_submit/_additional_codes_details.html.slim

Prior to this change, column width was relative to data.
This change fixes the layout by using columns
See: [TARIFFS-229](https://uktrade.atlassian.net/browse/TARIFFS-229)
**Before:**
**After:**

Fix align issue on approval page

---

app/views/workbaskets/edit_geographical_area/workflow_screens_parts/_area_details.html.slim

Prior to this change, `Description valid to` field was showing twice.
This change removes duplicate code
See: [TARIFFS-270](https://uktrade.atlassian.net/browse/TARIFFS-270)

Fix field that is showing twice

---

app/views/workbaskets/edit_geographical_area/steps/_main.html.slim
app/views/workbaskets/edit_geographical_area/steps/main/_memberships.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/_other_descriptions.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/view/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/edit_geographical_area/workflow_screens_parts/status_pages/_ready_for_export.html.slim

Prior to this change, some pages in the wedit geo workflow were missing or
had problems which caused the page to crash
This change fixes these issues/missing views.

Fix: Some crashes caused by missing/incorrect pages on edit geo workflow

---

config/locales/en.yml

Prior to this change, there was an error message typo to
'Edit geographical area' page
This change fixes that typo
See: [https://uktrade.atlassian.net/browse/TARIFFS-253](https://uktrade.atlassian.net/browse/TARIFFS-253)

Fix page error message typo

---

app/views/shared/vue_templates/_add_geo_areas_to_country_region_popup.html.erb

Prior to this change, `geographicalArea.geographical_code` was
supposed to be render but it was always resulted in rendering a `0`
This change replaces data driven string with a handcoded one.
See: [https://uktrade.atlassian.net/browse/TARIFFS-248](https://uktrade.atlassian.net/browse/TARIFFS-248)

Fix typo  on light box of 'Edit geographical area'

---

app/assets/javascripts/components/workbaskets/edit-geographical-area.js
app/views/workbaskets/edit_geographical_area/steps/main/_type.html.slim

Prior to this change, it was not visible which option was selected
This change uses JS in order to mimic read only for radio buttons, as
by default radio buttons do not support readonly attribute
See: [https://uktrade.atlassian.net/browse/TARIFFS-251](https://uktrade.atlassian.net/browse/TARIFFS-251)
**Before:**
**After:**

Fix disabled radio button on Edit geographical area

---

app/views/workbaskets/create_geographical_area/steps/review_and_submit/_geographical_areas.html.slim

Prior to this change, when a cross checker viewed cross check new
geo area page it crashed due to the partial being shared between
cross check edit geo area and create new geo area and the differences
between the two workbaskets in how they identify the geo area in
question
This change finds the instance of geo area in different ways depening
on whether it is edit or create to fix this issue.

Fix: Crash when viewing cross checker new geo area page

---

app/views/shared/vue_templates/_edit_geographical_area_membership_popup.html.slim

Prior to this change, there was a JS reference error that was cought by
Sentry
This change remove the invalid reference
Related to : [https://uktrade.atlassian.net/browse/TARIFFS-244](https://uktrade.atlassian.net/browse/TARIFFS-244)

Fix JS  disableLeaveDate ReferenceError

---

app/assets/javascripts/components/additional-codes-show-page.js
app/assets/javascripts/components/bulk-edit-additional-codes.js
app/assets/javascripts/components/bulk/measures/columns.js
app/assets/javascripts/components/find-measures.js
app/assets/javascripts/components/find-quotas.js

Prior to this change, the user would see a blank last updated field
when viewing a bulk edit workbasket.
This change removes this column.

Fix: Remove last updated field from bulk edit pages

---

Gemfile
Gemfile.lock
app/services/nomenclature_tree_service.rb
lib/tree_node.rb
spec/integration/chief_transformer/vat_excises_spec.rb
spec/lib/tree_node_spec.rb
spec/unit/tariff_synchronizer/base_update_spec.rb
spec/unit/tariff_synchronizer/logger_spec.rb
spec/unit/tariff_synchronizer/taric_update_downloader_spec.rb
spec/unit/tariff_synchronizer/tariff_downloader_spec.rb

Prior to this change, we used a gem that clashed with some other
features.
This change removes the gem and restores the tests that were temporarily
removed.

Refactor: Remove RubyTree gem and restore tests

---

app/services/nomenclature_tree_service.rb

Prior to this change, when muliple codes and suffixs were used sometimes
the wrong description was attached to a node.
This change uses sid to link the tables instead of using item_id and
suffix.

Fix: Correct description for nomenclature tree

---

app/models/workbaskets/edit_geographical_area_settings.rb

Prior to this change, we searched for original geographical area by
sid and id. This is unnecessary and occasionally causes issues
This change finds original geographical area by id only.

Fix: Correctly find original geographical area

---

app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb

Prior to this change, we were getting errors when adding a geo
area description.
This change stops these errors by referencing original_geographical_area
instead of the unassigned variable geographical_area.

Fix: Bug occurring when saving edited geo area workbasket.

---

app/views/workbaskets/edit_geographical_area/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim

Prior to this change, the copy told the user they were editing a
geo area when in fact they are cross checking it.
This change corrects this error.

Fix: Incorrect copy on cross-check geo area page

---

app/helpers/workbasket_workflow_helper.rb
app/views/workbaskets/workflows/approves/new.html.slim
app/views/workbaskets/workflows/cross_checks/new.html.slim

Prior to this change, links on the workflow pages would always
point to the find measures page, rather than the page on which
the user can find the resource about which they are interested in.
This change dynamically generates links to the appropriate resources.

Fix: Incorrect links on workflow pages

---

config/application.rb

Prior to this change, lib directory was auto-loaded, which is not the recommended practice and appeared to be causing an issue in production.
This change changes autoloading lib to eager loading (i.e. now loads up the lib directory at startup)
Tree in lib was not loading when browsing the nomenclature tree
https://uktrade.atlassian.net/browse/TARIFFS-205

Fix: Eager load lib directory

---

app/services/nomenclature_tree_service.rb

Prior to this change, if multiple valid indents existed they would all be returned. This change limits to just the latest indent.
This change uses SQL to specifically limit the indents returned.

Fix: nomenclature tree where multiple indents exist

---

app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb

Prior to this change, if a user tried to edit a geo area with no memberships,
and did not add any memberships, a server error would be raised.
This was due to settings_params['geographical_area_memberships'] being
nil and some lines in the settings saver trying to call methods on nil.
This change corrects this issue.

Fix: Server errors when editing geo area with no memberships

---

app/assets/javascripts/components/workbaskets/validation_errors_handler.js.coffee
app/assets/stylesheets/bootstrap_overrides.scss
app/assets/stylesheets/components/forms.scss
app/views/workbaskets/create_additional_code/_form.html.slim
app/views/workbaskets/create_additional_code/steps/main/_additional_codes.html.slim
app/views/workbaskets/create_additional_code/steps/main/_start_end_dates.html.slim
app/views/workbaskets/create_additional_code/steps/main/_workbasket_name.html.slim
app/views/workbaskets/create_certificate/_errors_summary.html.slim
app/views/workbaskets/create_certificate/steps/main/_certificate_code.html.slim
app/views/workbaskets/create_certificate/steps/main/_certificate_type_code.html.slim
app/views/workbaskets/create_certificate/steps/main/_description.html.slim
app/views/workbaskets/create_certificate/steps/main/_operation_date.html.slim
app/views/workbaskets/create_certificate/steps/main/_validity_period.html.slim
app/views/workbaskets/create_footnote/_errors_summary.html.slim
app/views/workbaskets/create_footnote/steps/main/_description.html.slim
app/views/workbaskets/create_footnote/steps/main/_footnote_type_id.html.slim
app/views/workbaskets/create_footnote/steps/main/_operation_date.html.slim
app/views/workbaskets/create_footnote/steps/main/_validity_period.html.slim
app/views/workbaskets/create_geographical_area/_errors_summary.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_code.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_description.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_operation_date.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_type.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_validity_period.html.slim
app/views/workbaskets/create_regulation/steps/main/_regulation_identifier.html.slim
app/views/workbaskets/create_regulation/steps/main/_regulation_name.html.slim
app/views/workbaskets/create_regulation/steps/main/_validity_period.html.slim
app/views/workbaskets/shared/_custom_errors_block.html.slim
app/views/workbaskets/shared/_errors_container.html.slim

Prior to this change errors were not listed inside
summary at the top of the page.
This change fixes this and by rendering the errors as
links to the actual form errors inside the summary following GDS 
style guides (See: [https://govuk-elements.herokuapp.com/errors/#summarise-errors)](https://govuk-elements.herokuapp.com/errors/#summarise-errors) 
**Resolves:** [TARIFFS-125](https://uktrade.atlassian.net/browse/TARIFFS-125)
**Before:**
**After:**

Fix error summary links

---

app/controllers/workbaskets/base_controller.rb
app/helpers/workbasket_helper.rb
app/views/workbaskets/main_menu_parts/_actions.html.slim

Prior to this change, users could not delete workbaskets.
This change allows users to delete workbaskets that are new, being edited,
or have been rejected by a cross checker or approver.

New: Add delete link for workbaskets that are not in cc/approval stages

---

app/views/certificates/certificates/search/_form.html.slim
app/views/footnotes/footnotes/search/_form.html.slim
app/views/geo_areas/geo_areas/search/_form.html.slim

Prior to this change user could not submit form by
pressing Enter key.
This change fixes this issue by changing the html of 
Search buttons from `a` to `button` 
**Relates to:** [https://uktrade.atlassian.net/browse/TARIFFS-285](https://uktrade.atlassian.net/browse/TARIFFS-285)

Fix 'Search' buttons

---

app/assets/javascripts/components/workbaskets/main_menu_interactions.js.coffee
app/views/workbaskets/main_menu_parts/_actions.html.slim

Prior to this change, the delete confirmation pop up was the browser
default, this change uses a custom style consistent with other confirmation
popups.

Fix: Add custom styling to delete confirmation pop up

---

app/assets/javascripts/components/workbaskets/edit-geographical-area.js

Prior to this change, if a user withdrew a edit geo area workbasket and went
to edit it again they would not be able to change the description start date
without changing the description
This change displays the option to edit the description start date at all times.

Fix: Always show description period validity start date on edit geo area

---

app/controllers/additional_codes/bulks_controller.rb
app/controllers/measures/bulks_controller.rb
app/controllers/quotas/bulks_controller.rb

Prior to this change, bulk edit additional codes, bulk edit
measures and bulk edit quotas workbaskets have delete links
that do not link to a valid page which crashes the app
This change corrects the way in which 'bulks' controllers handle
deleting of workbaskets to ensure they redirect to the home page
and behave in the same way as other workbaskets.

Fix: Delete bulk edit button crashing app

---

app/interactors/workbasket_interactions/edit_nomenclature/settings_saver.rb
app/models/workbaskets/edit_nomenclature_settings.rb
app/value_objects/workbasket_value_objects/shared/primary_key_generator.rb
db/migrate/20190712143348_add_workbasket_fields_goods_nomenclature_description.rb
db/structure.sql
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

Prior to this change, the workbasket was saving the data entered but not creating the items in the appropriate tables, e.g. goods_nomenclature_description and goods_nomenclature_description_period
tables.
This change saves the items in these tables.
https://uktrade.atlassian.net/browse/TARIFFS-203

Fix: Save the edit nomenclature wb setting as items

---

app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_ready_for_approval.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_ready_for_export.html.slim
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

Prior to this change, some edit nomenclature screens had a problem when
displaying the status information in the workflow.

Fix: display problem caused by my copy/paste :(

---

app/models/chapter.rb
app/services/nomenclature_tree_service.rb
app/views/nomenclature/chapters/show.html.erb

Prior to this change, if a Heading item (e.g. 710100000) had entries for bot producline_suffix 10 AND 80 an exception would be thrown.
This change treats headings with a suffix 10 as a 'heading group title'
See https://www.trade-tariff.service.gov.uk/chapters/71 for an example, where suffix 10 is displayed as a heading "I. NATURAL OR CULTURED PEARLS AND PRECIOUS OR SEMI-PRECIOUS STONES"
https://uktrade.atlassian.net/browse/TARIFFS-330

Fix: Nomenclature tree bug for heading group

---

app/interactors/workbasket_interactions/edit_nomenclature/settings_saver.rb

Prior to this change, the description was being assigned the validity date (copy and paste error while brain dead with cold)
This change correctly assigns the description.
https://uktrade.atlassian.net/browse/TARIFFS-333

Fix: Description wasn't being correctly updated during edit.

---

app/views/xml_generation/templates/metadata.builder

Prior to this change the metadata xml file did not use the required
compressed tag. This change adds this to metadata xml.

Fix: Add compressed tag to meta data

---

app/decorators/workbaskets/workbasket_decorator.rb
app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim

Prior to this change, we said 'nomenclature'
This change changes to use 'goods classification'
https://uktrade.atlassian.net/browse/TARIFFS-326

Fix: Change words used to describe edit nomenclature

---

app/assets/javascripts/vue_components/additional_codes/change-description.js
app/interactors/workbasket_interactions/bulk_edit_of_all_additional_codes/item_saver.rb
app/views/shared/bulks/_table_top.html.erb
app/views/shared/vue_templates/additional_codes/_change_validity_period.html.erb
spec/features/workbasket/additional_codes/find_and_edit_additional_codes/edit_additional_codes_spec.rb

Prior to this change, when a user edited an additional code there were new additional codes and related objects created in the database. The required behaviour was sometimes to update rather than create a new object.
This PR fixes this issue.

Fix: Edit additional codes

---

app/controllers/workbaskets/edit_nomenclature_controller.rb
app/controllers/workbaskets/manage_nomenclatures_controller.rb
app/services/nomenclature_tree_service.rb
app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb
db/migrate/20190725135752_add_original_description_to_edit_nomenclature_workbasket_settings.rb
db/structure.sql
spec/factories/chapter_factory.rb
spec/factories/goods_nomenclature_factory.rb

Prior to this change, the tree displayed descriptions even if they were
waiting for approval.
This change checks the status for published.
https://uktrade.atlassian.net/browse/TARIFFS-333

Fix: only display description in nomenclature tree if description published

---

app/forms/workbasket_forms/edit_nomenclature_form.rb
app/interactors/workbasket_interactions/edit_nomenclature/settings_saver.rb
app/views/workbaskets/edit_nomenclature/edit.html.erb
app/views/workbaskets/manage_nomenclatures/new.html.erb

Prior to this change, drop down selects were used.
This change uses text fields instead.

Fix: Change date inputs from selects to text fields

---

app/validators/goods_nomenclature_description_period_validator.rb

Prior to this change, it was possible to create a description with a
start date earlier than the nomenclature code start date,
This change prevents that.
https://uktrade.atlassian.net/browse/TARIFFS-214

New: add conformance rule, nomenclature desc start date

---

app/assets/javascripts/vue_components/custom-select.js
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim
app/views/workbaskets/create_quota/steps/main/_quota_precision.html.slim
spec/support/capybara_form_helper.rb

Prior to this change, we would not set a default value using
the custom-select vue component
This change introduces a new property that serves that scope
Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-187](https://uktrade.atlassian.net/browse/TARIFFS-187)
**After**

New: Extend selectize to support default value

---

app/models/goods_nomenclature.rb
app/views/goods_nomenclatures/_tree_node_content.html.erb
app/views/goods_nomenclatures/show.html.erb
app/views/nomenclature/chapters/show.html.erb
app/views/nomenclature/sections/show.html.erb

This change shows the user the currently accurate description for a goods commodity code. i.e if a change to the description is made, but it should not be applied until next year then it will not be shown until next year.
Previously, we were showing the latest description, regardless whether or not it was in it's validity period.

Show current nomenclature description

---

app/helpers/workbasket_workflow_helper.rb

Prior to this change, when a user was editing a nomenclature workbasket
the breadcrumbs linked to 'measures'.
This commit shows the correct 'Goods classification' link.

Fix: Show correct breadcrumbs for nomenclature workbaskets

---

app/assets/stylesheets/components/forms.scss
app/helpers/cross_check_helper.rb
app/views/workbaskets/create_measures/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/create_quota/steps/main/_order_number.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_details.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/workflows/approves/_form.html.slim
app/views/workbaskets/workflows/cross_checks/_form.html.slim
app/views/workbaskets/workflows/cross_checks/new.html.slim
spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb
spec/features/workbasket/measure/measure_creation_approval_spec.rb

Prior to this change, there was no heading on cross-check
nomenclature page.
This change adds the missing case. Further more with this commit
there were some more copy changes/fixes taken place on confirmation
/reject labels
Resolves [TARIFFS-331](https://uktrade.atlassian.net/browse/TARIFFS-331), [TARIFFS-112](https://uktrade.atlassian.net/browse/TARIFFS-112)
**AFTER**
> <img width="827" alt="Screenshot 2019-07-30 at 14 22 20" src="https://user-images.githubusercontent.com/6704411/62137346-b4106280-b2dd-11e9-94a5-b93c87a72b09.png">
> <img width="847" alt="Screenshot 2019-07-30 at 14 22 10" src="https://user-images.githubusercontent.com/6704411/62137347-b4106280-b2dd-11e9-9fef-9084c679e194.png">
> <img width="822" alt="Screenshot 2019-07-30 at 14 21 53" …

Fix: Add missing cross check heading

---

app/views/shared/vue_templates/_bulk_edit_records.html.erb

Display a warning message when selecting rows to for applying changes
on bulk editing
**Resolves:**  [TARIFFS-301](https://uktrade.atlassian.net/browse/TARIFFS-301)
**Before:**
**After**

Add a warning message when selecting rows for editing

---

Gemfile
app/controllers/log_in_controller.rb
app/helpers/auth_helper.rb
app/views/log_in/index.html.erb

This change is needed to mitigate against CVE-2015-9284. Installing the gem and
changing the get requests to our sso to post requests.
Our application running `authenticate_user!` before every controller action
so we cannot simply change the get requests made to our oauth provider to post requests
because we are redirecting all requests there if user is not logged in. Instead I have
added a simple view with a log in button to allow us to make post requests to our
oauth provider.

Fix: Oauth security issue

---

app/views/workbaskets/edit_nomenclature/edit.html.erb
app/views/workbaskets/edit_nomenclature/show.html.erb
app/views/workbaskets/shared/steps/review_and_submit/_edit_nomenclatures.html.erb

Prior to this change, the footnotes were not being displayed
This change displays all the footnotes for the nomenclature.
https://uktrade.atlassian.net/browse/TARIFFS-327

Fix: display the footnotes correctly for nomenclature edit

---

app/helpers/commodities_helper.rb
app/views/goods_nomenclatures/_tree_node_content.html.erb

This change creates a 'View measures' link when viewing nomenclatures.
The link will open up the measures search page with the commodity code
prefilled and listing matching measures.
https://uktrade.atlassian.net/browse/TARIFFS-325

New: Find Measures when viewing Nomenclatures

---

app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/show.html.slim

Previously summary of configuration was only visible when awaiting cross check or when cross check was rejected.
This changes allows summary to be visible everywhere
Resolves: [TARIFFS-360](https://uktrade.atlassian.net/browse/TARIFFS-360)

Display configuration summary

---

app/models/goods_nomenclature.rb

Prior to this change, any nomenclature description would be displayed
even if it had not yet been approved and published.
This change will only display descriptions with the status 'published'
https://uktrade.atlassian.net/browse/TARIFFS-333

Fix: Only display published nomenclature description

---

app/models/user.rb

Prior to this change, when a user was created in our db by signing into the dit sso for
the first time the user did not get assigned an id and it caused the application to crash.
This commit assigns an id when creating a new user and fixes the issue.

Fix: Create user from SSO bug

---

app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_next_step_links.html.slim

Prior to this change, there was a bug that the code would check for mode
== 'cross-check' but mode is always 'approve' (i.e. it's the action
approve/reject, not whether you are cross checking.)
This change no longer checks what mode it is. The link will show whether
you approved or rejected the basket.
https://uktrade.atlassian.net/browse/TARIFFS-346

Fix: Display 'Cross-check next workbasket' if available

---

app/controllers/application_controller.rb
app/controllers/goods_nomenclatures_controller.rb
app/controllers/nomenclature/chapters_controller.rb
app/controllers/nomenclature/sections_controller.rb
app/services/nomenclature_tree_service.rb
app/views/goods_nomenclatures/_tree_node_content.html.erb
app/views/goods_nomenclatures/show.html.erb
app/views/nomenclature/_sections_header.html.erb
app/views/nomenclature/chapters/show.html.erb
app/views/nomenclature/sections/index.html.erb
app/views/nomenclature/sections/show.html.erb
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb
spec/services/nomenclature_tree_service_spec.rb

Prior to this change, you could only view the current tree.
This change allows the user to specify a date and the tree will be calculated at this date.
https://uktrade.atlassian.net/browse/TARIFFS-207

New: Nomenclature can view the Nomenclature Tree at specific date.

---

app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim

Prior to this change, when submitting workbasket for edit nomenclature the link for 'withdraw' said it was not implemented but this has now been completed.
This change removes the 'not implemented' text.
https://uktrade.atlassian.net/browse/TARIFFS-371

Fix: Remove "(not implemented)" from withdrawal link

---

app/models/base_regulation.rb
app/models/modification_regulation.rb

Show regulation format as  8 digits field to be consistent. 
Resolves:[https://uktrade.atlassian.net/browse/TARIFFS-359](https://uktrade.atlassian.net/browse/TARIFFS-359)

Remove formatting from regulations

---

app/views/workbaskets/main_menu_parts/_main_menu.html.slim
spec/features/regulations_listing_spec.rb

The find and edit regulations page does not load due to missing data from HMRC in some explicit abrogation regulations (and perhaps others).
This change disables the find and edit regulations link until we receive correct data.

Fix: Temporarily disable find and edit regulations

---

app/views/workbaskets/edit_nomenclature/workflow_screens_parts/status_pages/_next_step_links.html.slim

despite being an approver, not a cross checker.
This change displays 'cross check next workbasket' link only for those
who are not an approver.
https://uktrade.atlassian.net/browse/TARIFFS-346

Fix: After approval on nomenclature a user could CC a basket 

---

app/views/workbaskets/edit_nomenclature/edit.html.erb

Remove Dates and Amounts caption

---

app/helpers/approval_helper.rb
app/views/workbaskets/shared/steps/review_and_submit/approval/_additional_code.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_edit_nomenclatures.html.erb
app/views/workbaskets/shared/steps/review_and_submit/approval/_geographical_areas.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_measures.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_quotas.html.slim
app/views/workbaskets/workflows/approves/new.html.slim

Prior to this change, cross-check partial templates were used on
approval.
This change introduce approval partial templates
Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-370](https://uktrade.atlassian.net/browse/TARIFFS-370)
**Before:**
**After:**

Fix: Display approve instead of cross-check

---

app/controllers/goods_nomenclatures_controller.rb
app/views/goods_nomenclatures/show.html.erb

Prior to this change, entering a code with spaces, or an invalid code
would throw an exception.
This change removes any non-digit values and handles an invalid code
without throwing an exception.

Fix: Nomenclature search didn't handle invalid searches well.

---

app/helpers/approval_helper.rb
app/views/measures/bulks/work_with_selected_measures.html.erb
app/views/workbaskets/bulk_edit_of_additional_codes/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/bulk_edit_of_measures/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_additional_code/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_geographical_area/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_measures/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/edit_nomenclature/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_bulk_edit_additional_codes.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_bulk_edit_measures.html.slim

Prior to this change, warning copy was not met
the copy of the designs. 
This changes uses the correct copy. 
This change also fixes a bug on approval pages.
Relates: [https://uktrade.atlassian.net/browse/TARIFFS-331](https://uktrade.atlassian.net/browse/TARIFFS-331)

Fix: warning copy on cross check pages

---

app/models/measure.rb

Prior to this change, the regulation code was displayed in taric format. Users requested
that the code be displayed in a different format, as it is on the other pages.
This change corrects this issue.

Fix: Formatting of regulation id for measures search

---

app/views/measures/bulks/_action_buttons.html.slim

There was a requirement to remove `changes` copy from submit button value
**Relates**: [https://uktrade.atlassian.net/browse/TARIFFS-373](https://uktrade.atlassian.net/browse/TARIFFS-373)

Remove changes copy from button

---

app/views/workbaskets/create_additional_code/steps/review_and_submit/_additional_codes_details.html.slim
app/views/workbaskets/create_measures/steps/review_and_submit/_measures_table.html.slim
app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change there were still some dates displayed
in wrong format.
This change fixes that.
Resolves: [TARIFFS-358](https://uktrade.atlassian.net/browse/TARIFFS-358)

Fix remaining date formats

---

app/assets/javascripts/vue_components/additional_codes/change-validity-period.js
app/assets/javascripts/vue_components/date-select.js
app/views/shared/vue_templates/additional_codes/_change_validity_period.html.erb

Prior to this change, date pickers did not display the defined dates
This change fixes this bug and also disables the start date per
requirements
Resolves: [TARIFFS-365](https://uktrade.atlassian.net/browse/TARIFFS-365)
**After**

Fix: Disable validity start date on addition.codes

---

app/views/workbaskets/create_quota/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, the page would error and crash when we tried to review/approve
or view a submitted quota. This was due to a change to the way we displayed dates.
The summary_of_configuration page was passing a string to the format_date method
instead of passing a date to it.

Fix: Broken page when reviewing/cross-checking/approving quota

---

app/assets/javascripts/components/bulk-edit-additional-codes.js

Prior to this change, user was able to delete additional codes
on bulc edit
This change temporarily disables this functionality
Resolves: [https://uktrade.atlassian.net/browse/TARIFFS-347](https://uktrade.atlassian.net/browse/TARIFFS-347)
**After**

Fix: Remove delete option on edit aditional codes

---

app/assets/javascripts/vue_components/bulk-edit-records.js
app/views/quotas/bulks/_action_buttons.html.slim
app/views/shared/bulks/_action_buttons.html.slim
app/views/shared/vue_templates/_bulk_edit_records.html.erb

This commit extends the functionality on bulk edit vue component
to display a heading above the records list. Also `changes` copy is
removed from submit buttons
**Relates:** [TARIFFS-373](https://uktrade.atlassian.net/browse/TARIFFS-373)
**After**

Add header on edit bulk records

---

app/controllers/goods_nomenclatures_controller.rb
app/views/nomenclature/_sections_header.html.erb

Prior to this change, searching for no value would crash.
This change defaults an empty search to '0000000000'
Also this change pads all entries to 10 characters, prevents user
entering non-digits and prevents more than 10 characters being entered.
https://uktrade.atlassian.net/browse/TARIFFS-377
https://uktrade.atlassian.net/browse/TARIFFS-378

Fix: Nomenclature search

---

app/assets/javascripts/vue_components/bulk-edit-records.js
app/views/shared/vue_templates/_bulk_edit_records.html.erb

Prior to this change, when a user was taking an action he could not
see any success notification
This change extends the bulk edit fuctionality to show success
messages. Currently as requested we are only showing message for
workbasket removals. If we need to we can now show messages for other
actions as well.
Resolves:[TARIFFS-266](https://uktrade.atlassian.net/browse/TARIFFS-266)
**After**

New: Add success notification on bulk edit actions

---

app/controllers/application_controller.rb
app/controllers/goods_nomenclatures_controller.rb
app/views/goods_nomenclatures/_tree_node_content.html.erb
app/views/goods_nomenclatures/show.html.erb
app/views/nomenclature/_sections_header.html.erb
app/views/nomenclature/chapters/show.html.erb
app/views/nomenclature/sections/index.html.erb
app/views/nomenclature/sections/show.html.erb
spec/features/workbasket/goods_nomenclature/goods_nomenclature_spec.rb

Prior to this change, the nomenclature date change was using a cookie to
remember the date chosen. This conflicts with the way the original
system used dates (within time_machine) to restrict searches etc.
This change uses a similar mechanism to continue to pass the date
parameters within the url.
https://uktrade.atlassian.net/browse/TARIFFS-378
https://uktrade.atlassian.net/browse/TARIFFS-333

Fix: Nomenclature date setting and search conflict

---

app/views/workbaskets/create_regulation/steps/main/_regulation_name.html.slim

Prior to this change, hint text was breaking in two lines.
This change fixes this by using the responsive wrapper
explicit on the form element

Make hint text one liner

---

app/views/workbaskets/create_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/create_footnote/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, the view footnote page and the review and submit footnote page were
missing some details.
This change adds description and associated goods codes to the view page and associated
goods code to the review and submit page.

Fix: Add description and associated goods code to view footnote screens

---

app/controllers/goods_nomenclatures_controller.rb

This change handles the case where searching for a non-existent chapter.
https://uktrade.atlassian.net/browse/TARIFFS-378

Fix: Searching for '0' commodity code crashed app

---

app/interactors/workbasket_interactions/create_footnote/initial_validator.rb

Prior to this change, when a user was creating a footnote and selected a footnote
type that could be associated with a goods commodity code, entered an incorrect
commodity code, but then changed to a footnote type that did not need a commodity code
the incorrect commodity code error still showed.
This change fixes the issue by only checking for commodity code errors if the footnote
type is one that takes a commodity code.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-395

Fix: Unnecessary commodity code warning for create footnotes

---

app/views/workbaskets/create_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/create_footnote/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, the associated measures and commodity code id's were shown
in arrays. This change removes the square brackets around the list of ids.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-393

Fix: Remove square brackets on view footnote page

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/cable.js
app/assets/javascripts/channels/download.js
app/channels/application_cable/channel.rb
app/channels/application_cable/connection.rb
app/channels/download_channel.rb
app/controllers/measures/measures_controller.rb
app/services/measure_service/download_measures.rb
app/views/measures/measures/_search_page.html.slim
app/workers/available_download_broadcast_worker.rb
config/application.rb
config/cable.yml
config/routes.rb
config/schedule.yml
db/structure.sql

Prior to this fix the download would timeout if it took longer than a
minute. Also, it blocked the process.
This fix uses a background job to create the csv and then uses web
sockets (action cable) to deliver the results.
https://uktrade.atlassian.net/browse/TARIFFS-335

Fix: Download Measures now uses Web Sockets to prevent timeout

---

app/interactors/workbasket_interactions/create_footnote/initial_validator.rb

Prior to this change, when a user was creating a footnote and selected a footnote
type that could be associated with a measure, entered an incorrect
measure, but then changed to a footnote type that did not need a measure
the incorrect measure error still showed.
This change fixes the issue by only checking for measure errors if the footnote
type is one that takes a measure.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-395

Fix: Unnecessary measure warning for create footnotes

---

app/controllers/workbaskets/edit_footnote_controller.rb
app/helpers/approval_helper.rb
app/helpers/cross_check_helper.rb
app/views/workbaskets/edit_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/_actions_allowed.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/_workbasket_details.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/_block.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/approves/_general.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/cross_check/_awaiting_cross_check.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_approval_rejected.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_awaiting_approval.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_awaiting_cross_check.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_cds_error.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_cross_check_rejected.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_published.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_ready_for_approval.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_ready_for_export.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/notifications/view/_sent_to_cds.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_approval_rejected.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_awaiting_cds_upload_create_new.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_cross_check_rejected.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_next_step_links.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_ready_for_approval.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_ready_for_export.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_edit_footnote.html.slim
app/views/workbaskets/shared/steps/review_and_submit/approval/_edit_footnote.html.slim

Prior to this change, there was no cross-check or approval process for edit footnotes.
This commit adds this workflow process.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-398
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-399

New: Edit footnotes cross check

---

app/views/workbaskets/create_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/create_footnote/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, if a footnote was created with a description that starts in the future
then the description does not show up on the summary of configuration and review and
submit pages.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-394

Fix: Show description for footnotes

---

app/value_objects/workbasket_value_objects/create_regulation/attributes_parser.rb

Prior to this change, the value of official journal number was always
'00'. Our expected behaviour Every time we create new regulations, we
need to put a value of "1" in the two fields officialjournal.number and
officialjournal.page
The reason for these two "journal" fields being "1' is so that Bit
Zesty can differentiate between UK and EU regulations on the Trade
Tariff Service - if both of these fields is "1", then this means it's a
UK regulation.
This change changes the hardcoded value from '00' to '1' for official
journal number.
https://uktrade.atlassian.net/browse/TARIFFS-404

Fix: Create Regualtion XML value for official journal number

---

app/helpers/approval_helper.rb

Prior to this change, it was missing
This change added it
https://uktrade.atlassian.net/browse/TARIFFS-274

Fix: Add header for create regulation approval

---

app/interactors/workbasket_interactions/edit_footnote/settings_saver.rb
app/interactors/workbasket_interactions/edit_geographical_area/settings_saver.rb
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_awaiting_approval.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/status_pages/_awaiting_cds_upload_edit.html.slim
app/views/workbaskets/shared/steps/review_and_submit/_edit_footnote.html.slim

Prior to this change, If a footnote description was changed but the start date was the same as the previous description then the application would create a new footnote rather than updating the existing one. This commit fixes this issue.
This commit also contains fixes for the edit footnote workflow.

New: Update existing description if start date is the same

---

app/views/workbaskets/create_additional_code/steps/main/_start_end_dates.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_type.html.slim
app/views/workbaskets/create_geographical_area/steps/main/_validity_period.html.slim
app/views/workbaskets/edit_geographical_area/steps/main/_type.html.slim

There was a  typo error that is now fixed. A small layout change 
also took place in order to render description in a single line

Update typo/layout on Geographical Area

---

app/views/layouts/govuk_template.html.erb
app/views/regulations/search/_form.html.slim
app/views/shared/vue_templates/_date_gds.html.erb
spec/features/regulations_listing_spec.rb

A Vue application should consists of a root Vue instance created with new Vue,
optionally organized into a tree of nested, reusable components. Either that
or work with single-file components.
Unfortunatelly current application initialises many vue instances that resulting
in undesirable side effects.
An quick workaround was to create a new clean instance that then can be
used on demand when it is required, in order to make proper components to work
**See:** [Vue Instance](https://vuejs.org/v2/guide/instance.html)
**See:** [Vue Single File Components](https://vuejs.org/v2/guide/single-file-components.html)

Fix issue with vue instance, use date-gds

---

app/interactors/workbasket_interactions/create_footnote/initial_validator.rb
app/interactors/workbasket_interactions/edit_footnote/initial_validator.rb

Prior to this commit, if a user entered an invalid measure_sid or commodity
code then it rendered a 'server error'.
This commit handles this issue and raises an error in the way we would expect.

Fix: Raise error for invalid measure_sids or commodity codes for create/edit footnote

---

app/controllers/footnotes/footnotes_controller.rb

Prior to this change, when a user searched for a footnote but entered an
invalid measure_sid then the page crashed.
This change stops the page crashing and renders 'no results found'
instead.

Fix: Footnotes searching by measure sid bug

---

app/views/additional_codes/bulks/submitted_for_cross_check.html.slim
app/views/quotas/bulks/submitted_for_cross_check.html.slim
app/views/workbaskets/bulk_edit_of_measures/submitted_for_cross_check.html.slim
app/views/workbaskets/create_additional_code/submitted_for_cross_check.html.slim
app/views/workbaskets/create_certificate/submitted_for_cross_check.html.slim
app/views/workbaskets/create_footnote/submitted_for_cross_check.html.slim
app/views/workbaskets/create_geographical_area/submitted_for_cross_check.html.slim
app/views/workbaskets/create_measures/submitted_for_cross_check.html.slim
app/views/workbaskets/create_quota/submitted_for_cross_check.html.slim
app/views/workbaskets/create_regulation/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_certificate/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_footnote/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_geographical_area/submitted_for_cross_check.html.slim
app/views/workbaskets/edit_nomenclature/submitted_for_cross_check.html.slim

Prior to this change, some links were missing from
submitted for cross check pages
This change adds the missing links
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-414](https://uktrade.atlassian.net/browse/TARIFFS-414)

Fix: This commit will add/fix links at submit pages

---

app/interactors/workbasket_interactions/create_footnote/initial_validator.rb
app/interactors/workbasket_interactions/edit_footnote/initial_validator.rb
app/models/footnote.rb
app/models/footnote_association_goods_nomenclature.rb
app/views/workbaskets/edit_footnote/show.html.slim
app/views/workbaskets/edit_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, all associated codes were displayed to a user when cross-checking or approving a footnote, regardless of any deletions.
This PR fixes this issue and only shows currently active associations to cross-checkers and approvers.

Fix: Show users correct information on associated codes

---

app/views/shared/vue_templates/_quota_section.html.erb
spec/features/workbasket/quota/quota_creation_validations_spec.rb
spec/features/workbasket/quota/quota_spec.rb

Prior to this change, month and day were disabled for Bi-Annual,
Quarterly and Monthly periods
This change removes the previously applied logic for dates based on
period type
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-423](https://uktrade.atlassian.net/browse/TARIFFS-423)

Fix period type quota start dates

---

app/controllers/bulks_base_controller.rb
app/controllers/measures/bulks_controller.rb

Prior to this change, if user tried to withdraw additional code(s) from a workbasket
in a way that would leave the workbasket empty, errors were being raised. This was
due to the workbasket no longer existing once it's contents had been deleted.
This caused issues in the measures/bulks_controller when some logic depended on
data from the now non existent workbasket.
This commit fixes these issues.

Fix: Withdraw additional code from workbasket causing error

---

app/interactors/workbasket_interactions/create_footnote/settings_saver.rb
app/interactors/workbasket_interactions/edit_footnote/settings_saver.rb

This PR fixes issues surrounding server errors being displayed on edit footnote and create footnote form screens when incomplete information was entered.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-392

Fix: Server errors generated from edit/create footnotes

---

app/assets/javascripts/components/bulk/measures/bulk-edit-measures.js
app/views/workbaskets/create_measures/steps/_duties_conditions_footnotes.html.slim

The ability to create and add footnotes from the create/edit measures pages does not work.
This functionality is available through the create/edit footnotes pages and this is how the users should be carrying out this task.
This PR deletes the add footnotes section of the create/edit measures pages.

Fix: Remove footnotes from measures page

---

db/migrate/20130207150008_add_oplog_columns.rb
db/migrate/20130208142043_rename_to_oplog_tables.rb
db/migrate/20130208170444_add_index_on_operation_date.rb
db/migrate/20151214224024_add_model_views_reloaded.rb

There are 4 migration scripts that add columns to tables it finds in the database.  On PaaS there are extra GIS tables that need to be skipped, otherwise the process will fail (and abort).  This would be only be a problem when creating a clean environment in PaaS. Luckily local initialisation is not affected.

Need to skip the GIS tables that the postgres postGIS extension creates.

---

app/views/quotas/bulks/work_with_selected.erb

Prior to this fix, when a user selected a quota to edit, but decided to cancel before creating the workbasket
the app crashed. This was due to an incorrect link on the cancel button.
This fix corrects this issue by redirecting the user to the home page after cancelling the edit quota
workbasket.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-424

Fix: Cancel edit quota bug

---

app/views/workbaskets/edit_footnote/workflow_screens_parts/_actions_allowed.html.slim

Prior to this change, when a user viewed a submitted edit footnote workbasket and
clicked 'withdraw basket from workflow' it showed a 'create footnote' screen with errors.
This was due to the button having an incorrect link.

Fix: Withdraw edit footnotes bug

---

app/interactors/workbasket_interactions/edit_footnote/initial_validator.rb

Prior to this change, if no codes are entered into the measure codes or commodity
codes text fields and nothing is changed then a server error is raised.
This is due to no guard clause to ensure that these codes are actually present.

Fix: Errors shown when no codes are entered

---

app/services/xml_generation/upload.rb

The filenaming convention has been agreed by HMRC and European Dynamics,
and the decision has been taken to omit the timestamp, which had been
included in the HMRC interface documentation. Therefore the filenaming
conventions are as follows:
For the Taric 3 XML file:
Using the example of the file from 2019 with an envelope ID of 142, the
filename will be DIT190142.xml, i.e.
- DIT, followed by
- the year (two digits), followed by
- the envelope ID (pre-padded with zeroes up to 4 digits), followed by
- .xml
For the metadata file:
As above, but with _metadata inserted before the .xml extension

Fix: Change DIT XML file naming convention

---

app/views/workbaskets/create_regulation/steps/_review_and_submit.html.slim

Prior to this change, workbasket details are not shown when viewing or
reviewing a Create Regulation Workbasket.
This change shows the deets.
https://uktrade.atlassian.net/browse/TARIFFS-462

Fix: Viewing workbasket details for create regulation

---

app/interactors/workbasket_interactions/create_regulation/settings_saver.rb
app/interactors/workbasket_interactions/edit_regulation/settings_saver.rb
spec/support/shared_contexts/form_savers/regulation_saver_base_context.rb
spec/support/shared_contexts/system/create_regulation_base_context.rb

Prior to this change, there was no validation on the inital letter.
This change forces the initial letter to be one of 'P,U,S,X,N,M,Q,A'
which are the new UK values.
https://uktrade.atlassian.net/browse/TARIFFS-459

Fix: Regulations should conform to the new UK initials 'P,U,S,X,N,M,Q,A'

---

app/interactors/workbasket_interactions/create_regulation/settings_saver.rb
app/interactors/workbasket_interactions/edit_regulation/settings_saver.rb
spec/support/shared_contexts/system/create_regulation_base_context.rb

Prior to this change, we removed the EU identifiers and replaced them
with UK ones. This change adds back the ability to use 'C' as an
identifier.
https://uktrade.atlassian.net/browse/TARIFFS-459

Fix: Allow C to be used as regulation identifier

---

app/controllers/workbaskets/workflows/base_controller.rb
spec/features/workbasket/cross_check_and_approval/cross_check_and_approval_spec.rb
spec/features/workbasket/measure/measure_creation_approval_spec.rb

Prior to this change, a user had to manually upload xml to our s3 bucket in order to be processed
by CDS.
This change uploads the xml once the workbasket is approved.
Note: This commit makes the upload run synchronously, i.e not in a sidekiq queue in order for us to
be able to more easily monitor/debug the process. This may need to be change to run async again
once the concept has been proven and any bugs ironed out.

New: Upload workbasket XML automatically upon approval

---

app/assets/javascripts/components/workbaskets/edit-footnote.js
app/views/workbaskets/edit_footnote/steps/main/_description_validity_start_date.html.slim

Prior to this change, there was a bug in edit-footnote.js
(probably there are more ...) which was preventing the put request to
go through as description validity could not been set.
This change fixes that bug and also is replacing the date picker with
the date-gds component
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-445](https://uktrade.atlassian.net/browse/TARIFFS-445)

Fix the issue with the  description validity date

---

config/sidekiq.yml

This commit temporarily stops the download xml worker from running in order to investigate issues relating
to the upload of data to our s3 bucket.

Temporarily stop download xml worker

---

app/interactors/workbasket_interactions/edit_regulation/settings_saver.rb
app/models/workbaskets/workbasket.rb
app/views/workbaskets/create_regulation/workflow_screens_parts/_summary_of_configuration.html.slim
app/views/workbaskets/edit_regulation/edit.html.slim
app/views/workbaskets/edit_regulation/workflow_screens_parts/_summary_of_configuration.html.slim

Prior to this change, when withdrawing a workbasket it was creating an
entry in the oplog for deleting the whole regulation.
This change deletes all the entries in oplog connected to this workbasket
rather than adding a delete entry. Also, hides the 'edit the ID' feature
as ID cannot be edited for regulations.
https://uktrade.atlassian.net/browse/TARIFFS-470

Fix: Withdrawing an edit regulation workbasket bug.

---

app/models/measure.rb
app/models/measure_type.rb
app/validators/measure_validator.rb
app/views/workbaskets/create_regulation/steps/main/_regulation_identifier.html.slim
lib/sequel/plugins/time_machine.rb

Prior to this change, if a measure type has a validity start date in the
future then it is not possible to create a measure that utilises this
type.
This change adds a new parameter for 'actual' method (include_future)
that will result in the method also returning objects that have a future
start date.
https://uktrade.atlassian.net/browse/TARIFFS-461

Fix: Allow Measures to use types with future start date.

---

app/views/workbaskets/edit_footnote/steps/review_and_submit/_footnote.html.slim
app/views/workbaskets/edit_footnote/workflow_screens_parts/_summary_of_configuration.html.slim

Showing original descriptions was causing issues when a footnote only had one description.
Disabling this functionality for now until we can work on the wider issue.

Fix: Bug around original description

---

app/models/xml_export/file.rb
app/services/xml_generation/upload.rb

Prior to this change, the year was added to the envelope ID. But
envelope ID also included the year.
This change no longer adds the year to the envelope ID and instead
ensures the envelope ID is reset at the start of each year.

Fix: XML export name

---

app/models/workbaskets/workbasket.rb

Prior to this change, if a user edited a gootnote, using a description validity start date that already existed,
then withdrew the workbasket and tried to submit again, the user would see a server error.
This was due to the withdraw process deleting the footnote description that was being edited so the second time
the user went to edit, it was not available to update.
This commit fixes this issue by stopping the footnote descriptions being deleted upon withdrawal.

Fix: Edit footnote after withdrawing bug

---

app/interactors/workbasket_interactions/create_certificate/initial_validator.rb

Prior to this change, only digits 1-9 were allowed in certificate codes, on create
certificate forms.
This fix corrects this issue to allow 0.

Fix: Allow 0 in certificate code

---

app/assets/javascripts/vue_components/edit-geographical-area-membership-popup.js
app/models/workbaskets/edit_geographical_area_settings.rb
app/views/workbaskets/edit_geographical_area/steps/main/_memberships.html.slim

Prior to this change, the join date on the membership table showed the start date of the geo area
as opposed to the start date of the membership. This PR fixes this issue.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-524

Fix: Geo area membership dates

---

app/controllers/workbaskets/workflows/base_controller.rb

Prior to this change, approving an additional code sometimes took user to a crash page.
This seems to be because the export worker is running synchronously and if the next page loads
before the job has finished the page crashes.
This change makes the worker run async which should ensure the user never gets to a crash page
for this reason.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-503

Fix: Additional code approval failing

---

app/forms/workbasket_forms/create_quota_association_form.rb
app/views/quota_associations/quota_associations/index.html.erb

Prior to this change the user could select a quota that has been end-dated.
This now blocks that - and corrects the header.
https://uktrade.atlassian.net/browse/TARIFFS-455

Fix: Ensure quota order has not been end-dated

---

app/assets/javascripts/components/quota-form.js
app/assets/javascripts/vue_components/date-gds.js
app/assets/javascripts/vue_components/quota-section.js
app/assets/javascripts/vue_components/quota-sections-manager.js
app/views/shared/vue_templates/_quota_section.html.erb
spec/features/workbasket/quota/quota_creation_validations_spec.rb
spec/features/workbasket/quota/quota_spec.rb

Prior to this fix, some data were removed when removing a section 
due to a watcher method inside the vue component. 
Since this logic is required when changing the section type I have
added an a parameter to capture this behaviour and allow the method
to be executed conditionally.
**Resolves:** [https://uktrade.atlassian.net/browse/TARIFFS-423](https://uktrade.atlassian.net/browse/TARIFFS-423)

Fix section data persistence

---

app/controllers/quota_suspensions/quota_suspensions_controller.rb

Prior to this commit, the view quota suspension periods page showed quota suspensions that had
already finished. This commit fixes this issue.

Fix: Show current quota suspensions periods

---

app/forms/workbasket_forms/edit_quota_suspension_form.rb

Prior to this commit, the quota suspension period is not saving.

Fix: Quota suspension not saving

---

app/assets/javascripts/vue_components/records-grid.js
app/views/shared/vue_templates/_records_grid.html.erb
app/views/workbaskets/create_additional_code/show.html.slim

I have added another property to record-grid component that can be used to hide locked column on demand
**Resolves** [https://uktrade.atlassian.net/browse/TARIFFS-516](https://uktrade.atlassian.net/browse/TARIFFS-516)

Hide locked column on record grid on demand

---

app/forms/workbasket_forms/create_quota_association_form.rb
app/views/workbaskets/create_quota_association/edit.html.erb

Prior to this change, the validation was not checking against the latest
quota order.
This change check the end date of the latest version of the quota.
https://uktrade.atlassian.net/browse/TARIFFS-585

Fix: end date validation for quotas

---

app/views/workbaskets/main_menu_parts/_main_menu.html.slim

Prior to this commit, our training environment was crashing due to use not having a trade tariff reference app in
our training environment that we can link to. The link was looking for an env variable which did not exist which
caused the app to crash, this commit fixes this issue by only showing the link if the ENV variable exists.
This is a short term fix, in the long term we need to set up a reference app in the training environment.

Fix: Training crash due to reference bug

---

app/forms/workbasket_forms/create_quota_association_form.rb

Prior to this change the validation was checking the wrong entry.
This fixes the validation by sorting on the quota_order_number_sid rather than the oid.
https://uktrade.atlassian.net/browse/TARIFFS-455

Fix: create quota association validation

---

app/controllers/quota_associations/quota_associations_controller.rb
app/models/concerns/workbasket_helpers/association.rb
app/models/quota_association.rb

Prior to this fix. The Quota Association wasn't actually deleted
(we were waiting for implementation of the CDS cycle)
This commit changes that so whenever the basket is published the item
is marked deleted.
https://uktrade.atlassian.net/browse/TARIFFS-552

Fix: Quota Association Deletion issues

---

app/controllers/workbaskets/create_quota_suspension_controller.rb
app/forms/workbasket_forms/edit_create_quota_suspension_form.rb
app/views/workbaskets/create_quota_suspension/edit.html.erb

This commit changes EditQuotaSuspensionForm to EditCreateQuotaSuspensionForm. This fix is needed
because editquotasuspensionform needs to be used to edit and existing quota suspension.

Fix: Rename editquotasuspensionform

---

app/controllers/quota_suspensions/quota_suspensions_controller.rb
app/controllers/workbaskets/edit_quota_suspension_controller.rb

This PR addresses two issues with editing quota suspension periods.
1) Errors not correctly showing on the new page.
2) All quota suspension periods being shown in the find and edit page. The intended functionality is that only suspension periods which have the status 'published' should be shown.

Fix edit quota suspension bugs

---

app/controllers/workbaskets/edit_quota_suspension_controller.rb
app/forms/workbasket_forms/edit_edit_quota_suspension_form.rb
app/views/workbaskets/edit_quota_suspension/edit.html.erb

This PR fixes two bugs in the edit quota suspension feature.
1) Editing an existing quota suspension period creating a new quota suspension period.
2) Page crashing when editing a quota suspension period and changing the validity dates to outside the dates of the definition.

Fix edit quota save bug

---

app/forms/workbasket_forms/edit_quota_suspension_form.rb

Prior to this change, when a user selects a quota order number to edit they sometimes get an error
saying that the quota order number has an end date which means it is not editable, when it does not
have an end date.
This change ensures that the user is always editing the latest quota order number period.

Fix: Edit latest Quota order number

---

app/forms/workbasket_forms/edit_edit_quota_suspension_form.rb

Prior to this change, a user could enter an end date which started before the start date, or vice
versa, without seeing an error.
This issue was due to the way that the dates were formatted.

Fix: Date validation errors on edit quota suspension period

---

app/views/workbaskets/create_footnote/show.html.slim
app/views/workbaskets/create_geographical_area/show.html.slim
app/views/workbaskets/create_measures/show.html.slim
app/views/workbaskets/create_quota/show.html.slim

Prior to this fix, when 'View'ing a Create Footnote workbasket that had been rejected, the link was redirecting to edit_footnote instead of create_footnote.
Also, create "Geographical Area", "Measure" and "Quota" all were missing a parameter so their calls were failing as well.
https://uktrade.atlassian.net/browse/TARIFFS-471

Fix: "Edit <workbasket object type>" link had exception or failed

---

app/views/workbaskets/edit_quota_suspension/workflow_screens_parts/_actions_allowed.html.slim

Prior to this change, when a user edited a quota suspension period then went to the
view page and clicked 'withdraw/edit' they were shown a crash page.
This was due to the button linking to the create suspensions url instead of the edit
suspension url.

Fix: Incorrect withdrawal link on view edited quota suspension page

---

Gemfile
Gemfile.lock

Prior to this change, security alerts were raised for:
rubyzip: < 1.3.0
simple_form: < 5.0.0
This change upgrades:
rubyzip: 1.3.0
simple_form: 5.0.1

Fix: rubyzip and simple_form upgrade for security

---

app/services/nomenclature_tree_service.rb

Prior to this change, when viewing dates in the future it was possible
to view nomenclature items that were not yet published.
This change ensures all nomenclatures are published.
https://uktrade.atlassian.net/browse/TARIFFS-638

Fix: displaying nomenclatures not published

---

app/interactors/workbasket_interactions/create_nomenclature/initial_validator.rb
app/services/nomenclature_tree_service.rb
app/views/workbaskets/create_nomenclature/edit.html.erb
config/locales/en.yml

Prior to this change, it was possible to create a nomenclture that could
not be displayed as it didn't correspond to a vaild section/chapter.
This change makes sure that one exists. Also, this change will display a
nomenclature item that had previously been 'orphaned' due to it's indent
being a higher value than expected. (E.g. If an item had an indent of 3
and the next item had an indent of 5, then the item with 5 would not
have been displayed as it was considered to be detached. This is now
displayed so that it can be deleted if necessary.
https://uktrade.atlassian.net/browse/TARIFFS-639

Fix: Ensure new nomenclatures match with a Chapter

---

app/services/xml_generation/node_message.rb

Prior to this change, both edit and delete quota suspension workbaskets are rendering the XML for a delete
transaction.
This is due `record_is_a_pending_deletion?` returning true anytime the model in question is a quota
suspension period.
This change instead looks at the type of workbasket and only returns true if the workbasket type is a
DeleteQuotaSuspensionSettings which fixes the issue.

Fix: Edit/Delete quota suspension period xml bug

---

app/views/workbaskets/edit_quota_suspension/submitted_for_cross_check.html.slim

Prior to this change, the withdraw link from the 'view' page of edit quota suspension wb
was linking to create quota suspension form, causing an error. This commit fixes this issue.

Fix: Withdraw link from 'view' for edit quota suspension workbasket

---

app/interactors/workbasket_interactions/create_nomenclature/settings_saver.rb
app/views/workbaskets/manage_nomenclatures/new.html.erb
config/locales/en.yml

Prior to this change, conformance rules were not blocking creation.
This change corrects traps conformance errors.
https://uktrade.atlassian.net/browse/TARIFFS-212

Fix: conformance rules for create nomenclature

---

app/validators/quota_order_number_validator.rb

Prior to this change, ON2 was not being triggered when a new quota is
created with the same quota order number.
This change checks if there is an open-ended quota order number already
with the same quota_order_number_id
https://uktrade.atlassian.net/browse/TARIFFS-164

Fix: Quota Order Number conformance error ON2

---

app/interactors/workbasket_interactions/create_nomenclature/initial_validator.rb
config/locales/en.yml

Prior to this change, indents could be set to 0 for a new commodity
code.
This value is used only for section chapters, so should be prevented
from being added as a child code.
https://uktrade.atlassian.net/browse/TARIFFS-654

Fix: Prevent indents being set to 0

---

app/assets/javascripts/vue_components/change-conditions-popup.js
app/views/shared/vue_templates/_condition.html.erb

Prior to this change, the conditions were not showing certs correctly
and not populating the current values when performing bulk edit.
This change references the correct values.

Fix: Conditions Mechanics for Measure/Quota

---

app/models/base_regulation.rb

Prior to this change, there were some unecessary calculations that
expected the 2nd and 3rd digits to represent the year.
This change deletes the unecessary calculations as the 2nd and 3rd
characterrs are not necessarily the year and the calculations were no
longer needed/used.
https://uktrade.atlassian.net/browse/TARIFFS-658

Fix: the formatting of the regulation ID

---

app/models/concerns/form_api_helpers/regulation_search.rb
app/models/regulations_search_pg_view.rb
db/migrate/20191202145535_change_regulations_search_pg_view.rb
db/structure.sql

Prior to this change:
- it would only match from the beginning of the description string
- it would return values from the oplog table not the view.
https://uktrade.atlassian.net/browse/TARIFFS-27
https://uktrade.atlassian.net/browse/TARIFFS-665
https://uktrade.atlassian.net/browse/TARIFFS-666

Fix: Regulation search issues

---

app/decorators/workbaskets/workbasket_decorator.rb
app/forms/workbasket_forms/edit_create_quota_blocking_period_form.rb
app/helpers/approval_helper.rb
app/helpers/cross_check_helper.rb
app/views/workbaskets/create_quota_blocking_period/edit.html.erb
app/views/workbaskets/shared/steps/review_and_submit/approval/_create_quota_blocking_period.html.erb
app/views/workbaskets/shared/steps/review_and_submit/approval/_edit_quota_blocking_period.html.erb

Prior to this change, cross checking and approving create/edit quota blocking periods was causing crashes due to some of the helper methods not having the correct options for the new workbasket types and some of the necessary views being missing.
This PR fixes these issues.

Create quota blocking period approval bugs

---

app/interactors/workbasket_interactions/create_quota/settings_saver.rb
app/models/quota_order_number.rb
app/models/workbaskets/create_quota_settings.rb
app/models/workbaskets/workbasket.rb
app/views/workbaskets/create_quota/steps/main/_licensed_block.html.slim
app/views/workbaskets/create_quota/steps/review_and_submit/_message.html.slim

License Quotas should not store anything in the Quota tables:
quota_associations
quota_order_numbers
quota_order_number_origins
quota_order_number_origin_exclusions
quota_definitions
https://uktrade.atlassian.net/browse/TARIFFS-93
https://uktrade.atlassian.net/browse/TARIFFS-673

Fix: License Quotas do not save any info in the Quota tables.

---

app/models/measure_type.rb

Prior to this change, License Quota measure types were hidden from this
form as they were expected to be edited via the Find Quota screens. This
is not now possible, so they need to access via the Find Measure.
https://uktrade.atlassian.net/browse/TARIFFS-514

Fix: Measure Type search on Find/Edit Measure page

---

app/views/workbaskets/shared/steps/main/_check_a_additional_code_description.html.slim

Prior to this change, it wasn't clear that on the Create Quota pages
when the user checks for a commodity code, we only check if it's
currently a valid commodity code - we cannot tell which date they may
want to check.
This change adds some explanation.

Fix: help text for the Commodity Code check

---

app/assets/stylesheets/components/forms.scss
app/assets/stylesheets/components/measure-components.scss

This change removes some gratuitous spacing around duty expressions.
https://uktrade.atlassian.net/browse/TARIFFS-660

Fix: Minor layout change for duty expression

---

app/assets/javascripts/vue_components/change-conditions-popup.js
app/assets/javascripts/vue_components/components-coordinator.js
app/assets/javascripts/vue_components/conditions-coordinator.js
app/assets/javascripts/vue_components/measure-condition.js
app/assets/javascripts/vue_components/sub-quota-definitions.js
app/assets/stylesheets/components/layout.scss
app/views/measures/measures/_search_form.html.erb
app/views/quotas/quotas/_search_form.html.erb
app/views/shared/vue_templates/_change_footnotes.html.slim
app/views/shared/vue_templates/_measure_origin.html.slim
app/views/shared/vue_templates/_quota_section.html.erb
app/views/shared/vue_templates/_quota_sections_manager.html.erb
app/views/workbaskets/shared/regulations/_regulation_identifier_help_text.html.erb
app/views/workbaskets/shared/steps/duties_conditions_footnotes/_footnotes.html.slim
features/page_objects/create_measure_page_elements.rb

Prior to this change, it was not easy to remove a component or condition if it was the only one and data was entered into it.
This change shows the 'Remove' link if more than one item or if the one item has data in it.
https://uktrade.atlassian.net/browse/TARIFFS-84

Fix: Allow component and conditions to be removed.

---

app/assets/javascripts/components/measure_form.js
app/controllers/goods_nomenclatures_controller.rb
app/validators/measure_validator.rb

Prior to this change, future codes would fail validation and not appear
when checking the code descriptions..
This change allows future codes.
https://uktrade.atlassian.net/browse/TARIFFS-645

Fix future nomenclature search

---

app/assets/stylesheets/components/select.scss
vendor/assets/stylesheets/selectize.bootstrap3.scss

Prior to this change, the electize-input changes height when values are
selected.
This change changes the display type to block so this stops happening.
https://uktrade.atlassian.net/browse/TARIFFS-681

Fix: More selectize-input freaky styley

---

app/views/additional_codes/additional_codes/_search_page.html.slim
app/views/certificates/certificates/search.html.slim
app/views/footnotes/footnotes/search.html.slim
app/views/geo_areas/geo_areas/index.html.slim
app/views/measures/measures/_search_page.html.slim
app/views/quotas/quotas/_search_page.html.slim
app/views/regulations/index.html.slim
app/views/workbaskets/edit_certificate/edit.html.slim
app/views/workbaskets/edit_footnote/edit.html.slim
app/views/workbaskets/edit_geographical_area/edit.html.slim
app/views/workbaskets/shared/_edit_base.html.slim

Across all of the search screens, there is a link to "Add a new one instead".
This is inaccessible, because the term needs to make sense out of context.
Changed to
'Alternatively, <a href="{url}">create a new xxxx</a>'
https://uktrade.atlassian.net/browse/TARIFFS-696

Fix: Change "Add a new one instead" text

---

app/views/geo_areas/geo_areas/search/_form.html.slim

This commit removes the start and end date filters and adds hint text under the remaining search
categories to explain to the user what each one does.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-695

Fix: Changes to geo area search page

---

app/views/workbaskets/shared/_action_links.html.slim

This commit adds text to explain to users that they should save progress before using the previous
page link.
https://uktrade.atlassian.net/jira/software/projects/TARIFFS/boards/127?selectedIssue=TARIFFS-703

New: Add guidance for using 'previous page' link

---

app/assets/javascripts/components/find-quotas.js
app/searches/quotas/search_filters/license.rb
app/views/quotas/quotas/_search_form.html.erb

Prior to this change, Quota search form had an 'Additional Code' field
and was displayed in the table. But there is never an additional code
on a Quota so should be removed.
Also, remove ability to search for a specific license ID
https://uktrade.atlassian.net/browse/TARIFFS-697
https://uktrade.atlassian.net/browse/TARIFFS-698

Remove Additional Code from Quota Search

---

app/assets/stylesheets/gds_overrides.scss

Prior to this change, some other CSS changes caused the 'submitted'
notice to be mis-aligned.
https://uktrade.atlassian.net/browse/TARIFFS-718

Fix: Submitted text alignment.

---

app/interactors/workbasket_interactions/create_measures/settings_saver.rb
app/services/code_parsing_service.rb
config/locales/en.yml

Prior to this fix:
1. Entering a commodity code exception that had more than 10 characters  would be truncated. Changed so that it flags an error.
2. Blank lines in Commodity Code field would cause an error
https://uktrade.atlassian.net/browse/TARIFFS-684

Fix: Create Measure validation
